### ISSUE TITLE
Embedded youtube videos causing automatic switching to safari

### ISSUE THREAD

**Issue by oscarvgg** [Simbul/baker#528] opened 2012-11-03 18:13 UTC
I have an app that has been working nicely since iOS 5.0, but now I’m having a problem.

In iOS 6, when I reach a dossier that has an embedded youtube video, it automatically switches to safari. And if i switch back to my app, the video is not there, it shows a blank space where it was supposed to be.

Hope you can help me

**Comment by folletto** [comment] 2012-11-22 18:52
How is the video embedded?

You might want to check Issue #510, seems the same issue. :)

**Comment by roninboy** [comment] 2012-12-19 13:23
I found that if I remove the User Agent references from the BakerAppDelegate.m (which are determining the new Youtube player options) - you can revert to the old flash embed code (which although deprecated) will still work.
The old player will allow fullscreen in any orientation. It also avoids all the issues with audio sessions, pausing problems etc.

**Comment by folletto** [comment] 2013-01-19 22:57
I'm closing this due to the lack of follow-up. Reopen at need.

**Closed as completed by folletto** 2013-01-19 22:57 UTC
Labels: Waiting follow-up

**Comment by rengen** [comment] 2013-02-28 18:15
Hello sorry for reopening this issue, but i have exactly the same problem with my applications that use the old embeded code of youtube videos.
@roninboy , Please can you tell with more details, wich lines exactly we have to delete from the BakerAppDelegate.m, in order to play the youtube videos.
thanks

**Comment by roninboy** [comment] 2013-03-01 09:33
Remove the following lines from the top of the file:
(void)initialize { // Set user agent (the only problem is that we can't modify the User-Agent later in the program) // We use a more browser-like User-Agent in order to allow browser detection scripts to run (like Tumult Hype). NSDictionary *userAgent = [[NSDictionary alloc] initWithObjectsAndKeys:@"Mozilla/5.0 (compatible; BakerFramework) AppleWebKit/533.00+ (KHTML, like Gecko) Mobile", @"UserAgent", nil]; [[NSUserDefaults standardUserDefaults] registerDefaults:userAgent]; [userAgent release]; }

**Comment by rengen** [comment] 2013-03-01 10:29
@roninboy Thanks, i will try it....

**Comment by rengen** [comment] 2013-03-04 17:18
@roniboy.
Thanks for the answer, but i can't find the piece of code inside the BakerAppDelegate.m.
Stange or what???
I enclose a screenshot.
![xcode](https://f.cloud.github.com/assets/1504483/217606/8fc5cbc2-84ef-11e2-8b09-02b277fe528f.png)

**Comment by folletto** [comment] 2013-03-04 17:33
Hello :)

The reason is simple: you are using an old version of Baker. :)

Update first to the latest version from the website (currently 4.0) and see if the issue is still there. :)
If not, then try the fix. :)

**Comment by rengen** [comment] 2013-03-04 19:30
Thanks (grazie) Davide, i will try it.
My main concern is that i use the Laker framework, and the switching from Laker to Baker i'm affraid to don't produce more problems....
And of course i have to update 6 applications!!!
