### ISSUE TITLE
can't add any html pages

### ISSUE THREAD

**Issue by fenix66** [Simbul/baker#78] opened 2011-04-06 15:14 UTC
Hi

I have a really weird problem. I have downloaded Baker, downloaded sample html pages, put it all in xcode , build  and everything works flawlessly.So next logical step was to put my own html and test how it will look , I put my html files in book folder , build and all works ok.
I have changed a little my html, build, and get white screen with something like this "Mac OS X 2 some weird signs TextEncodingx-mac-centraleuroman;29This resource fork intentionally left blank"
and from now I'm unable to do anything with baker , I tried to clean project , change html's , put back your sample htmls , nothing works , always white screen with this text.
What is the problem? I think it's something simple but I can't figure it out.

**Comment by Xm4s** [comment] 2011-04-07 19:04
Uhm... that's weird indeed.

Other than cleaning the project have you also tried to delete the app from iOS Simulator? Sometimes reinstalling the app over a previous installation lead to these kinds of error.

If this don't help... well, I'm sorry but without seeing the .html set that caused the problems I'm a bit clueless :)

**Comment by folletto** [comment] 2011-05-04 20:54
Hi Fenix, did the suggestion work out in the end? :)

**Comment by folletto** [comment] 2011-05-23 22:49
We are closing this, if the problem is still there please comment with more details. :)

**Closed as completed by folletto** 2011-05-23 22:49 UTC
Labels: Bug
