### ISSUE TITLE
vertical position of book on reopening

### ISSUE THREAD

**Issue by anjimi** [Simbul/baker#584] opened 2012-12-11 14:34 UTC
After downloading the latest master today, I am having a problem, if I exit app while reading a book, on reopening the app the book is positioned with the top of the page cropped off, and a grey gap at the bottom of the screen, which I've worked out by loading a screenshot into photoshop, is 20px.

If I go back to the shelf and reopen the book it loads fine.

**Comment by ghost** [comment] 2012-12-11 15:06
This is also happening in my app.

Steps to replicate:
1. Open a book/magazine
2. Swipe through a couple of pages (replicate normal use)
3. Press the 'Home' button on your device.
4. Open the app by selecting it in Newsstand.

Result: The current page jumps up about 20 pixles. The interesting thing is that the index also displays above this 20px bottom border that has been created. It's almost as if the entire app has been pushed up. But as previously stated: if you go back to the shelf and reopen the book/magazine it displays normally again.

**Comment by folletto** [comment] 2012-12-11 15:12
20px is the size of the iOS status bar, probably there's a bug in the code that handles it at runtime.

**Comment by ghost** [comment] 2012-12-13 14:47
Hi Davide,
I've had a couple of attempts at fixing this bug but I have been unsuccessful so far. Have you found the code that has been causing this bug? :)

Mitchell

**Comment by folletto** [comment] 2012-12-13 15:31
Nope, we are still working on other tasks right now. When we get here we'll update the issue, unless someone else is able to fix it. :)

**Comment by ghost** [comment] 2012-12-13 15:48
Thanks. I'll see if I can fix it.

I'll post the code in here if I do. :)

**Comment by Simbul** [comment] 2013-01-05 17:10
We couldn't reproduce the bug with either of the lists of steps you mentioned. Which version of iOS are you using?

We could, however, trigger the same bug with the following step:
1. Open a book in portrait mode
2. Rotate the device to landscape mode
3. Double tap to make the status bar appear
4. Close the app
5. Reopen the app: the page jumps down 20px

**Comment by ghost** [comment] 2013-01-05 18:08
I'm using iOS 6 and the latest version of Baker. To make sure it wasn't a fault in my publication I tested this on the provided Study In Scarlet book which produced the same bug.

All I have to do to replicate is open the app, download and open a book, press the home button and then tap to open the app again. The page I was on is displayed but it jumps up 20px.

I've been actively searching for a solution for the past couple of weeks but I have not found one.

**Comment by boss333** [comment] 2013-01-08 21:10
I have the problem when the application is configured in orientation portrait.

The code i used to fix the problem.

In AppDelegate.m :

``` objective-c
- (void)applicationWillEnterForeground:(UIApplication *)application
{
    // Called as part of the transition from the background to the inactive state; here you can undo many of the changes made on entering the background.
    #ifdef BAKER_NEWSSTAND
    // do nothing
    #else
    NSArray *books = [ShelfManager localBooksList];
    if ([books count] == 1)
        [((BakerViewController *)self.rootViewController) CorrectionBug20Pixels];
    #endif
}
```

In BakerViewController.h :

``` objective-c
- (void)CorrectionBug20Pixels;
```

In BakerViewController.m :

``` objective-c
- (void)CorrectionBug20Pixels
{
    [self willRotateToInterfaceOrientation:self.interfaceOrientation duration:0];
    [self performSelector:@selector(hideBars:) withObject:[NSNumber numberWithBool:YES] afterDelay:0.5];

    [self startReading];   
}
```

**Comment by ghost** [comment] 2013-01-08 22:48
Unfortunately this code failed to fix the bug with my app.

**Comment by buildc0de** [comment] 2013-01-26 02:01
I'll look into fixing this one next :-)

**Comment by buildc0de** [comment] 2013-01-26 14:44
Was able to reproduce:
1. Open 'A Study In Scarlet'.
2. Press the 'Home' button.
3. Re-open the app from Newsstand.

The red line under the title jumps up by about 20 px.

**Comment by buildc0de** [comment] 2013-01-26 21:46
Oops, committed to the wrong branch :-) Will redo...

**Comment by Simbul** [comment] 2013-01-29 12:53
Finally I've been able to reproduce this as well, with the steps @waywalker specified above.

We'll look into the pull request :)

**Comment by buildc0de** [comment] 2013-02-17 14:21
Re-implemented the fix in 45ac6f4.

**Comment by winmhtun** [comment] 2013-03-07 01:54
I couldn't fix this issue by using waywalker's fix. When I applied the fix, the entire page goes down for about 20px, which leaves a blank space at top 20 px, when the app starts. And when I click Home button and re-enter the app, the page goes up and is fit in the ipad-screen.

**Comment by winmhtun** [comment] 2013-03-07 06:07
Thanks to @waywalker , just managed to implement a fix for page getting pushed up issue when it re-enters. Like I said,  when I applied the fix mentioned by @waywalker , the entire page is pushed down by 20px when view starts to appear. So to get that work properly, I created a boolean to enable that method only when the app goes into background. 

1) created boolean to track if app goes into background. 

<pre>
<code> 
- (void)viewWillDisappear:(BOOL)animated {
    [self saveBookStatusWithScrollIndex];
}
- (void)saveBookStatusWithScrollIndex {
    if (currPage != nil) {
        bookStatus.scrollIndex = [currPage stringByEvaluatingJavaScriptFromString:@"window.scrollY;"];
    }
    [bookStatus save];
    appGoesBackground = YES;
    NSLog(@"saved status");
}
</code>
</pre>

2) call viewDidLayoutSubviews method when the app gets back from background.

<pre>
<code>
- (void) viewDidLayoutSubviews {
    if(appGoesBackground){
         [self adjustScrollViewPosition];
    }
}
</code>
</pre>

This might not be a perfect solution. Let me know if it works :) Cheers !

**Comment by fcontreras** [comment] 2013-03-07 21:59
:( not working for me.. added both @waywalker one and @winmhtun.. the issue of the gap at the botton got fixed but now Im still dealing with the top white gap :(

I'll let u know

**Comment by fcontreras** [comment] 2013-03-07 22:35
This seems to work for me

```
Index: BakerViewController.h
===================================================================
--- BakerViewController.h   (revision 38)
+++ BakerViewController.h   (working copy)
@@ -75,6 +75,7 @@

     BOOL userIsScrolling;
     BOOL shouldPropagateInterceptedTouch;
+    BOOL appGoesBackground;

     UIScrollView *scrollView;
     UIWebView *prevPage;
Index: BakerViewController.m
===================================================================
--- BakerViewController.m   (revision 38)
+++ BakerViewController.m   (working copy)
@@ -431,10 +431,19 @@
     NSLog(@"    Unlock page changing");
     [self lockPage:[NSNumber numberWithBool:NO]];
 }
+
+- (void) viewDidLayoutSubviews {
+    if(appGoesBackground){
+        [self adjustScrollViewPosition];
+    }
+}
+
 - (void)adjustScrollViewPosition {
     int scrollViewY = 0;
     if (![UIApplication sharedApplication].statusBarHidden) {
-        scrollViewY = -20;
+        if (!appGoesBackground) {
+            scrollViewY = -20;
+        }
     }

     [UIView animateWithDuration:UINavigationControllerHideShowBarDuration
@@ -1772,6 +1781,7 @@
         bookStatus.scrollIndex = [currPage stringByEvaluatingJavaScriptFromString:@"window.scrollY;"];
     }
     [bookStatus save];
+    appGoesBackground = YES;
     NSLog(@"saved status");
 }
 - (void)didReceiveMemoryWarning {
Index: IndexViewController.m
===================================================================
--- IndexViewController.m   (revision 38)
+++ IndexViewController.m   (working copy)
@@ -183,6 +183,13 @@
     [self fadeOut];
 }

+- (void)viewDidLayoutSubviews {
+    [self setPageSizeForOrientation:[UIApplication sharedApplication].statusBarOrientation];
+    [self setActualSize];
+    [self setIndexViewHidden:self.isIndexViewHidden withAnimation:NO];
+
+}
+
 - (void)rotateFromOrientation:(UIInterfaceOrientation)fromInterfaceOrientation toOrientation:(UIInterfaceOrientation)toInterfaceOrientation {
     BOOL hidden = [self isIndexViewHidden]; // cache hidden status before setting page size
```

**Comment by buildc0de** [comment] 2013-03-08 21:33
@winmhtun I just downloaded the latest master, applied [this fix](https://github.com/Simbul/baker/pull/675/files) and I don't seem to be able to reproduce the "entire page goes down for about 20px" issue. 

What are your exact steps?
Can you also attach a screenshot?

**Comment by fcontreras** [comment] 2013-03-08 21:44
Im not with the latest master.. but the issue was reproducible on the latest stable downloadable from the Baker Site.
You should be able to reproduce by just opening any book on the newsletters mode.

**Comment by benoitchantre** [comment] 2013-03-08 21:45
You need to quit the app and to relaunch it.
You will see the shift from the top when you open the app.

**Comment by buildc0de** [comment] 2013-03-10 03:14
After much poking, I was able to enter the problematic state a few times, but couldn't reproduce it reliably. It seems to be related to "afterDelay:0.5" in:

```
[self performSelector:@selector(hideBars:) withObject:[NSNumber numberWithBool:YES] afterDelay:0.5];
```

I went ahead and introduced a variable as suggested by @winmhtun's.

**Comment by benoitchantre** [comment] 2013-03-11 11:42
@waywalker: I'm trying your latest fix on a project with a vertical index and I can see that the index is moved down by 20px.

**Comment by buildc0de** [comment] 2013-03-11 15:15
@benoitchantre: I thought it might ;-) Couldn't reproduce to confirm. Looks like indexView needs its own variable as well. Will improve the fix further.

**Comment by Simbul** [comment] 2013-03-11 22:19
Fixed by @waywalker in pull request #675.

**Comment by buildc0de** [comment] 2013-03-11 22:22
@Simbul, the fix needs another slight improvement as reported by @benoitchantre :-) I should submit it shortly...

**Comment by Simbul** [comment] 2013-03-11 22:24
Ok, we'll wait for the new pull request :)

**Comment by buildc0de** [comment] 2013-03-12 00:12
@benoitchantre, please give the new version a try and let me how it works out. I wish I could reproduce easily :)

**Comment by benoitchantre** [comment] 2013-03-12 09:12
@waywalker, I have downloaded the source from your branch "issue-584-scrollview-position".

Then, to test the issue, I have set the project to use the standalone mode and did two changes in index.css from "a-study-in-scarlet" to make the index vertical.

changes to index.css
line 19: **background: rgba(0, 240, 240, 0.9);**
line 74: **display: block;**

It should look like that when the index is shown
![Capture d e cran 2013-03-12 a 09 58 58](https://f.cloud.github.com/assets/1521015/247853/26308dc8-8af3-11e2-84c2-481cffb0bc72.png)

When the app is launched for the first time, you can see that the index is moved down

Here's a screen capture taken when the index is hiding
![Capture d e cran 2013-03-12 a 09 56 30](https://f.cloud.github.com/assets/1521015/247847/caca2a7a-8af2-11e2-9a31-f2394f9905ac.png)

If the app is already running in the background, the vertical position of the index is ok.

I hope it helps.

Update: described in issue #774

**Comment by bobbytung** [comment] 2013-03-13 04:55
@waywalker Thanks for the improvement, I've tried. and list what happened 
- index:
  fixed: no more 20px in the bottom.
  bug: in book.json, when you set "-baker-index-height": null, it will crash, and you have to add 20px to the value.
- pageview:
  fixed: no more 20px in the bottom.
  bug: added 20px to every page, full page design will scroll and doesn't feel good to designer.

**Comment by buildc0de** [comment] 2013-03-16 21:53
@benoitchantre, I am thinking this issue ("When the app is launched for the first time") is possibly related, but a new one. The current one deals with "vertical position of book on reopening". In other words, the issue manifests only on returning from background. The cumulative effect of dcc10de and 0f77a87 is that the new code gets executed only on returning from background as well, so it can't be contributing to what you're seeing. Shall we create a new issue and close this one off? :-)

@bobbytung, the "bug: added 20px to every page" issue was present in the first version of the fix (dcc10de). Please make sure to apply 0f77a87 as well. As for the crash, could you please open a new issue?

**Comment by benoitchantre** [comment] 2013-03-18 20:28
@waywalker, I'll open a new issue in a few days, at the moment I have not enough time.

**Comment by Simbul** [comment] 2013-03-23 14:21
We've merged in #763, which should take care of the issues.

I'm going to close this discussion, as it has been going on for a very long time and has strayed from the original topic quite a bit.

Please open a new issue for any lingering bug.

**Closed as completed by Simbul** 2013-03-23 14:21 UTC
Labels: Bug

**Comment by benoitchantre** [comment] 2013-03-24 16:24
I have opened a new issue about the index position when you launch the app.
It's #774.

**Comment by anjimi** [comment] 2013-04-19 13:55
Great to see this issue resolved. Thank you @waywalker
