### ISSUE TITLE
Opening a new book does not reset the current page, possibly leading to a crash

### ISSUE THREAD

**Issue by andreacampi** [Simbul/baker#39] opened 2011-01-06 19:10 UTC
How to replicate:
- in the sample book add a link to a different book; the link must appear on a page that is higher than the number of pages in the second book (e.g.: I added the link on page 4, linking to a book of only 1 page);
- navigate to that page;
- send Baker to the background;
- go back to foreground, click on the link.

Baker will crash with:

<pre>
2011-01-06 20:06:26.160 Baker[79463:40b] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSMutableArray objectAtIndex:]: index 3 beyond bounds [0 .. 0]'
</pre>

Immediate fix: reset the current page to 1 when opening a new book (and store it to NSUserDefaults).
Longer term fix: keep separate "current pages" per book.

**Comment by Xm4s** [comment] 2011-01-07 11:46
Hi!

Thanks for pointing out this!
I've looked into this bug and the problem is in your commit request.

If you reset currPageNumber to 1 only when the saved value of currPageToLoad is 0 (which in my calculation was impossible even before your contribution)... well, the chance you are resetting the variable to 1 are equal to 0 :P

I'm fixing this with the bug pointed out in the issue #36.

**Comment by Xm4s** [comment] 2011-01-07 12:28
Fixed with the commit https://github.com/Simbul/baker/commit/b8a6d2e3a28d12e4842c214489400cfced893125
As for issue #36 I'll wait for a positive feedback on the fix before closing this up.

**Comment by andreacampi** [comment] 2011-01-07 13:31
Well, this is different than issues #37/#38. Reproducing the problem with page 0 is probably impossible with unmodified sources (barring any bugs).

This issue however is 100% reproducible, see the steps I outlined above.

**Comment by andreacampi** [comment] 2011-01-07 13:45
Uhm, I saw you reverted the change that protects against currPageToLoad=0.

As I said, I agree it _should_ never happen, but you shouldn't assume it never will.

Imagine the app was just started but we lose focus immediately (for instance, an SMS comes in) before we have even completed -initBook:
In that case, rootViewController.currentPageNumber will still be nil (it's not set in RootViewController:-init) so -saveLastPageReference will probably save lastPageViewed=0.
In that case, reading it back _will_ get a 0 here.

Actually, in my commit I meant to protect again this particular scenario in -saveLastPageReference, but I botched it:

<pre>
    if (lastPageViewed != 0) {
</pre>


That's just plain wrong, sorry about that :( It should probably be:

<pre>
if (rootViewController.currentPageNumber > 0) {
</pre>


Anyway, the bottom line is, you should never trust that something will _never_ happen; a bug in other parts of code may lead to this invariant not being true, and that will positively crash the app. I think you'll agree that's not nice :)

**Comment by Xm4s** [comment] 2011-01-07 14:07
I completely agree with you, even if it shouldn't be possible it's better to reduce any chance of the app crashing down, and in fact I didn't revert your change on lastPageView value check before saving it :)

However, as you have said here, the check as it is need a quick fix, I'll apply that as soon as I finish writing this, thanks for pointing it out.

Back to the topic of this issue, I try the step to reproduce the bug (link on page 5 a .hpub with only 3 pages) and it seems that everything works pretty well with the last commit. Could you please confirm that?

**Comment by andreacampi** [comment] 2011-01-07 14:28
Works for me, too. Thanks for looking at this :)

**Comment by Xm4s** [comment] 2011-01-07 15:33
Thank you for your precious support on the project :D
I'm closing this up.

**Closed as completed by Xm4s** 2011-01-07 15:33 UTC
Labels: Bug
