### ISSUE TITLE
Submission process

### ISSUE THREAD

**Issue by transmitter** [Simbul/baker#79] opened 2011-04-09 19:46 UTC
My hpub app was rejected because it was supposed to be submitted to the iBookstore not the app store. Is there a way to save future submitters the same time I just lost and is there anyone that can hook me up with a link to step by steps for that iBookstore submission? I have downloaded the epub check to run the book through as this seems to be a requirement?

http://code.google.com/p/epubcheck/

Thanks!

**Comment by folletto** [comment] 2011-04-09 21:23
Uhm could you explain it better? Baker Framework is designed to build App Store applications, not "books" for the iBook Store.

**Comment by transmitter** [comment] 2011-04-10 18:14
I received the following regarding my submission:

"Hello Adam,

Thank you for submitting A Face A Name to the App Store.

We've completed the review of your app, but cannot post this version to the App Store because it did not comply with the App Store Review Guidelines, as detailed below:

```
* 2.21: Apps that are simply a song or movie should be submitted to the iTunes store. Apps that are simply a book should be submitted to the iBookstore"
```

I dont know what my next step is. Any help would be hugely appreciated.

**Comment by folletto** [comment] 2011-04-10 18:18
Probably you created a book that is text only, the kind of thing that Apple created the iBook Store for.
If that's a correct hypothesis, you should use Baker for _design_ books, or rich photographic books, or HTML5 books with videos, animations and sounds. In other terms: anything that's not possible in epub (or: iBook, Kindle).

**Comment by transmitter** [comment] 2011-04-10 18:23
It has some hyperlinking, font replacement and a huge amount of images. It is only slightly more complicated than the example app on the Baker website. You can see some page examples on the website where the PDF is presently available. Its extremely image/css heavy. In fact the only reason I haven't yet submitted to kindle is because it contains so many images.

http://books.wellandgood.ca

**Comment by folletto** [comment] 2011-04-10 18:26
Uhm yes, from the example it looks clearly a case for Baker: iBook (epub) doesn't support these things. You should probably ping back Apple.

**Comment by transmitter** [comment] 2011-04-10 18:42
Thanks for that. I will do exactly that. Cheers!

**Comment by transmitter** [comment] 2011-04-14 20:46
My request for a review was met with the same response - it should be reformatted for epub and submitted to the ibook store. Im really confused. An Apple rep was kind enough to call and give me the bad news - how many books have been published using Baker? I have to admit - this feels like a giant waste of time.

**Comment by folletto** [comment] 2011-04-14 21:23
Well, it's hard to tell because not all the authors tell us, but so far we have counted at least 7 of them, from quite simple ones to more evolved ones. Also, as I've told you, you can't reproduce what you are making with epub ("it should be reformatted for epub"), so it's really an arbitrary decision from their side.

**Comment by transmitter** [comment] 2011-04-14 21:39
I submitted your http://itunes.apple.com/gb/app/5x15-tokyo/id399691024?mt=8 5x15 example along with my appeal request. If you could help out with those other 7 links that would be greatly appreciated. Its been 3 full months since starting the process to get into the app store and its clear to anyone who looks that the book I've designed is not appropriate for .epub format.

**Comment by ghost** [comment] 2011-04-24 06:49
Uhm. Ithink that the problem (for apple) is that you sell books by paypal and it's available also on pdf on your platform. My first answer is: we have to think at a dinamically changing text, so they can't say it's a book. Hpub, for example. We can even think at tools to cusotmize on the fly the html. Just some thougths.

**Comment by folletto** [comment] 2011-04-24 14:24
That's a really good point. :)

**Comment by ghost** [comment] 2011-04-24 18:14
:-) there's another solution: tools. I know you wnat the user interface minimalist,and it's a good idea, so instead of having the default ui, we could think at a second level, a second layer, a second browser, on the top, with show/hide functions, to be customized in html, something similar to navigation.html, but always on. We could use for twitter, for audio player, video player, and so on. Could be a tools.htm. Or could be the same navigation.html ... Why not...
This second page, 'always on' but with some show hide functions, could be 'linked' to the chapter we're reading with some commands, perhaps even a simple link, sharing cookies, with embeds from the web.
Just ideas :-)

**Comment by folletto** [comment] 2011-04-24 18:32
Thanks for this feedback. It's something already in planning, that is going to collect a serie of feedbacks we received both from there, Twitter and mail.

That's why we worked so much at the double-tap function: it's going to be there. ;)

**Comment by Simbul** [comment] 2011-05-04 20:53
Hey transmitter,
any luck with your submission? Did you at least manage to get a more sensible explanation?

Also, in case someone else needs the information, the list of books published with Baker can be found here: http://bakerframework.com/books

**Comment by transmitter** [comment] 2011-05-04 20:59
Thanks for posting that link. I'm still guessing as to the reasons why it was rejected - there were no technical errors. At the moment I am working on supplementary video content & interactivity to add to it in order to perhaps better meet their criteria for not being in the iBookstore.

**Comment by gabalese** [comment] 2011-05-09 19:48
I was wondering if the same rejection criteria apply for italian developers. I downloaded one of the eBook App made with Baker, "Un post sotto l'albero", which appears to be 'just a book' according to Apple terms (although _beautifully_ designed).

**Comment by folletto** [comment] 2011-05-09 22:02
As it happens with the other apps, it's more probably due to different people that check them. :)

**Comment by gabalese** [comment] 2011-05-09 22:45
Could well be. But the most intriguing question should be: where should an italian developer sell his iBook, given that iBookstore is not currently active in Italy?

**Comment by folletto** [comment] 2011-05-09 22:54
It is active. :)

"Q: Is iBooks available in every country with an App Store?
A: Yes, iBooks and the iBookstore are available in all App Store countries. iBookstore content varies by country."
http://support.apple.com/kb/HT4059

Since 28th of May 2010: http://www.apple.com/it/pr/library/2010/05/07ipad.html

**Comment by gabalese** [comment] 2011-05-09 23:13
Its content varies, quite sure; italian readers have plenty of Project Gutenberg books to choose from :) Since there is no trace of self-publishing or publishing houses on iBookstore IT, I am under the impression that your iBook won't be distributed through iBooks.

**Comment by ghost** [comment] 2011-05-10 10:00
Yes: it's not easy. I don't know italian publishing houses on ibookstore. In last 6 months there are some on the web, and they are starting now to sell some hundreds of books from their own websites.

**Comment by inventionarts** [comment] 2011-06-02 17:17
Apple is definitely pushing book-like apps to the iBookstore. One likely reason for them rejecting this app is that they've introduced "fixed layout" eBooks, an extended form of ePub that enables many of the presentation mechanisms afforded by Webkit, including Javascript interactivity, CSS3 animations and effects, and embedded audio and video. (We work with this format.) There are limitations, mostly around the difficulty of managing touch events, as these are commandeered by the iBooks UI. One large difference is an inability to implement any Ajax or indeed any functionality that hits a server: no external connections. 

At the moment, though I cannot say for sure, the meaningful utilization of external server content or functionality could be the basis for an appeal: you simply cannot implement these in iBooks.

At the moment! There's a rev of ePub forthcoming, called ePub 3. It provides for all of the above, and it is anticipated that Apple will support, as they have been reportedly active on the IDPF ePub standards committee that defined this update.

**Comment by folletto** [comment] 2011-06-02 21:13
I really don't know about the Apple guideline. We keep receiving notification of people that were able to publish successfully (I'm a little late in updating the Baker Published books page, there's a really excellent one), so even I can understand the rejection somehow, surely the line is incredibly blurred.

Do you have any example of such iBook with a "fixed layout"? I wasn't able to find a reliable source, and I abandoned the search inside the Apple documentation after an unsuccessful research.

I'm following ePub 3 since a few months before the release of Baker - well, before we even started coding - and it seems another book-centric approach, without any _requirements_ for a specific rendering mode - exactly like ePub 2. While ePub 3 looks like an excellent step forward, I still don't understand the need of such a complicated standard, when we do have HTML5. It could have been just an extension of it, instead of a limitation of it plus lots of other details (and there are features afaik still missing that again Baker does, like the book:// url scheme). :)

**Comment by folletto** [comment] 2011-06-20 20:55
Ok, I suppose I can close this issue since there's not much we can do at this time. We'll reopen if something new happens. :)

**Closed as completed by folletto** 2011-06-20 20:55 UTC
Labels: Discussion
