### ISSUE TITLE
Loading 3 books in chain using book protocol

### ISSUE THREAD

**Issue by RichHelms** [Simbul/baker#473] opened 2012-08-27 19:35 UTC
I used a modification of the Laker example as my base book. Then using the link to book://....hpub loading the Baker example. Then in Baker I tries to load another book with book:// that was a variation of the Laker book

The sim crashed giving error

```
2012-08-27 14:58:09.785 LPQ[12300:15203] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSRegularExpression enumerateMatchesInString:options:range:usingBlock:]: nil argument'
*** First throw call stack:
(0x181f022 0x1197cd6 0x17c7a48 0x17c79b9 0x281d40 0x28296a 0x14654 0x14535 0x60af 0x7d9e 0xfd11 0x15785d 0x17f3936 0x17f33d7 0x1756790 0x1755d84 0x1755c9b 0x19b17d8 0x19b188a 0x48f626 0x2396 0x2305)
terminate called throwing an exception
```

My guess is the original book is in the book folder. The new is loaded in "Private Documents" folder. Then when the second tries to call the third it is again loading into the "private documents" folder over the second.

Has anyone done a series of calls A loads B loads C...?

What I am trying to create is a core book which calls others. If over loading the second book is the issue, is there a way to call back to the original book?

Thanks.

**Comment by folletto** [comment] 2012-08-27 23:08
It should work even when chaining multiple books, but it might be also a bug. I think I have to ask you a few more questions to be able to make an hypothesis:
1. Which version of Baker are you using? 
2. Does the `book.json` file in the books refer to _different_ URLs?
3. Could you include a longer debug log?
4. Have you tried doing this? https://github.com/Simbul/baker/wiki/It%27s-crashing%2C-exploding-or-any-other-issue

**Comment by RichHelms** [comment] 2012-08-28 00:01
1. Latest
2. That is a great question. I don't think I set that correctly. Let me fix that tomorrow and try again

Rich Helms

**Comment by folletto** [comment] 2012-08-28 00:23
Latest from MASTER on github, or 3.2 from the website? ;)

**Comment by RichHelms** [comment] 2012-08-28 00:35
3.2 from the website. Is that the latest?

**Comment by folletto** [comment] 2012-08-28 11:30
The latest stable, yes. Then you might give a try of the current master in development: click Code at the top of the page here and then download the ZIP and test with it. :)

**Comment by RichHelms** [comment] 2012-08-28 15:00
I updated the URLs to correct them
Tried with 3.2 from site and latest code. Both failed on the second link. Here is the scenario
Using laker book as base. In it link to bakerbook
This loads and works fine. Now in that book link to laker book
Both of these are on the site. The second fails. 
Thanks
PS, I started with a Timex Sinclair then a Commodore 64 also but I had a diskette drive. My Timex was cassette so I can relate.

**Comment by folletto** [comment] 2012-08-28 15:05
Thanks. We got the links in email if you want to remove them from here. :)
We should be able to check it tomorrow. :)

**Comment by RichHelms** [comment] 2012-08-28 15:08
Thanks.

**Comment by RichHelms** [comment] 2012-08-29 18:06
BTW on the latest code I tested on audio and video are both failing. The interactive page in Laker has video and audio

**Comment by RichHelms** [comment] 2012-08-29 19:45
Audio/video issues may be mine

**Comment by Simbul** [comment] 2012-08-29 21:52
We just finished investigating the issue. The short version is: make sure `Introduction.html` in `lakerbook` is saved as UTF8.

Longer version: we could reproduce the bug, but we also noticed that the crash was happening even when embedding `lakerbook` as the default book in Baker.
This ruled out both downloading and multi-book management as possible causes.

We tracked down the crash to a line in `PageTitleLabel.m` that was parsing the HTML file to extract its `<title>`. Unfortunately this function is not as resilient as the one loading the HTML into a `UIWebView`, so the wrong encoding can make it fail.

We have added a guard (in commit e6dca88) that should hopefully make situations like this one easier to debug in the future. It will also silently fail for that specific page, without crashing the whole application.

@RichHelms please let us know if saving `Introduction.html` as UTF8 fixes your original issue.

**Comment by RichHelms** [comment] 2012-08-30 13:51
Simbul - Thanks. I edited that file on my PC with an older editor and it converted the file.
I am going to start with fresh files and test today. I'll get back with the results.

**Comment by folletto** [comment] 2012-09-03 19:22
Hello @RichHelms, is everything ok? :)

**Comment by RichHelms** [comment] 2012-09-03 19:29
I have been working on writing my samples. Struggling some with Laker so am
going to back off to the base Baker format.
On Wed I am driving to North Carolina for my son's wedding so I will not be
working on this after tomorrow for a week

Thanks for asking

Rich

From:  Davide Casali notifications@github.com
Reply-To:  Simbul/baker
<reply+i-6482471-0cd26410d87f8558624dbf9319ccbfb184d7ae71-2229584@reply.gith
ub.com>
Date:  Monday, September 3, 2012 3:22 PM
To:  Simbul/baker baker@noreply.github.com
Cc:  Richard Helms rich@wsws.ca
Subject:  Re: [baker] Loading 3 books in chain using book protocol (#473)

Hello @RichHelms https://github.com/RichHelms , is everything ok? :)

 ‹
 Reply to this email directly or view it on GitHub
https://github.com/Simbul/baker/issues/473#issuecomment-8245369 .

**Comment by folletto** [comment] 2013-01-19 23:00
I hope the problem was solved by now. Given the lack of follow-ups in the last 5 months, I'm closing this. Reopen if needed. :)

**Closed as completed by folletto** 2013-01-19 23:00 UTC
Labels: Support
