### ISSUE TITLE
IndexView size set to different size than expected

### ISSUE THREAD

**Issue by Bobramyl** [Simbul/baker#312] opened 2012-02-10 19:09 UTC
Hello,

I've worked with baker / laker for some time and with last update, my navigation menu is gone. I've also searched git issues for a solution and I've seen that it's already implemented as a fix, BUT it doesn't seem to work (meaning the patched version is still not working).

the problem is probably this:
2012-02-10 19:54:17.591 MUNI[5107:207] Set size for IndexView to 10x200 (constrained from 10x200)

my JSON:

```
    "orientation": "portrait", // only portrait orientation in my book
    "zoomable": false,

    "-baker-background": "#666666",
    "-baker-vertical-bounce": true,
    "-baker-index-height": 200,
```

I've also tried to add 
    "-baker-index-width": 768 but this solution will break the scrolling which is then not working. It's not scrolling even if set index-width to > 786, which I assumed should be at least temporary fix (i could manually calculate width), but it's not. Am using last version of baker / laker and it's just somehow bugged. 

If you help me with this issue, I will repay tenfold and within 3 - 4 weeks I will present complete implementation of shelf since am developing huge project for university which will be used as distribution channel for all their e-books (and it's goin to be powered by baker, also with ASIHTTPRequest framework for async Ebook downloading). I've also started to rewrite baker as standalone class, so it might be also interesting. Just a thing - am testing navigation on clean patched version without any changes.

( Ofc I was kiddin about the part I will share my work only if you help me, I am so glad for what you developed and I will share everything I can :)

Thanks for your time and for any help you can provide, you guys do a great job.

George

**Comment by folletto** [comment] 2012-02-10 19:19
Thanks George. ;)
And wow, it seems you are doing a pretty huge work there! :)

So, about your issue, could you clear me out first what version are you using? The latest MASTER from GitHub, or the latest version from the website (3.1)?

A thing that you can check immediately, is the real size of the index you are loading. If you use floats and similar it might be that the Objective-C side of things can't read correctly the size. Try to set body width and/or height in CSS first, and see if something changes. :)

**Comment by Bobramyl** [comment] 2012-02-10 21:02
Am using MASTER from GitHub. 

I logged my actual values from index view:

```
-> page width 768
-> page height 1024
-> index width 10
-> index height 200
-> actual index width 10
-> actual index height 200
```

So it seems that it takes 10px out of view through the 

```
    indexWidth = [self sizeFromContentOf:webView].width;
```

 and that's it. So it seems that i have problem that somewhere in my CSS is wrong body width? I've checked it two times and I also tried to set width:768px to body, but it seems unaffected. I then tried to manually override the value I get from view by adding another line (indexWidth = 768 && indexWidth = 1500) but that only shows menu, scroll is still not working.

**Comment by folletto** [comment] 2012-02-10 21:45
Uhm ok, we need to look into it. What was the last version working for you?

(is there also any way that you could send us your index.html?)

**Comment by Bobramyl** [comment] 2012-02-10 23:03
If you can provide me with na email adress, I will send you the whole pack, which is probably better idea anyway. My email is info@chuckdesign.cz , so you can send it there, then we can continue discussion here

**Comment by folletto** [comment] 2012-02-10 23:08
info@bakerframework.com :)

**Comment by Simbul** [comment] 2012-02-16 22:33
Hey @Bobramyl, I've spent some time digging into the book you sent us.
It's really hard to tell why the index bar is not able to detect size correctly with all the javascript and CSS involved. I've tried removing various bits and pieces from it without being able to get to a single root cause.

That said, there's a very easy fix you can put in place: replace the two `meta viewport` lines inside `index.html` with:

```
<meta name="viewport" content="width=2000; height=200; initial-scale=1.0; maximum-scale=1.0; user-scalable=no;" />
```

This will make your bar visible and scrollable (you don't need to specify either `-baker-index-width` or `-baker-index-height` in book.json).
Of course the values for width and height in the `meta` declaration will have to correspond to the size of your bar.

Let me know if this fixes the issue for you :)

**Comment by Bobramyl** [comment] 2012-02-20 13:19
Hey @Simbul,

I really, really appreciate your help. Yes, it really worked. The problem is apparently somewhere in .css, since there is really a lot of them sometimes overlaping each other. I will dig it into this later, but it works flawlessly as temporary fix. I hope I will be able to repay your help soon.

Ps. sorry for my late answer, I was out of... well out of there :)

Thanks again

George

**Comment by Simbul** [comment] 2012-02-20 21:22
No problem George. I'm glad it's working now.

I'm closing this issue. If you decide to dig into it and find out something that's worth sharing, you can open another issue so other people can benefit from it :)

**Closed as completed by Simbul** 2012-02-20 21:22 UTC
Labels: Support

**Comment by tstegart** [comment] 2012-03-31 23:28
We may need to reopen this. I couldn't get the index height to work by setting it in the book.json file. It seemed to have no effect and always seemed to show a page way larger than my index page. Setting the size of the content in the HTML seems to be the only way to get it to work.

**Comment by folletto** [comment] 2012-04-01 00:09
That's expected: the size of the HTML is what makes the index view size, while the book.json is there as a "fallback". :)
See the wiki: https://github.com/Simbul/baker/wiki/Adding-an-Index-Bar-to-your-publication

We should see if we can make the book.json parameter more "effective", maybe.

**Comment by tstegart** [comment] 2012-04-01 00:34
Thanks.

**Comment by JamesBrocklehurst** [comment] 2012-04-18 15:00
Don't know if this helps, but adding certain "-baker-" parameters, such as "-baker-index-bounce" and "-baker-vertical-pagination" to the manifest file seems to create the issue.
