### ISSUE TITLE
Problems with Index Function

### ISSUE THREAD

**Issue by dhart23746** [Simbul/baker#148] opened 2011-09-21 10:16 UTC
We are working on a publication with Baker framework and have been impressed... but have had problems with the double-tap index function loading on our test Ipad device. 

When we build the app in Xcode and run it in the simulator, everything works fine. But when we try to test it on the device, everything works ... except for the double tap index function. 

We tried to recreate the problem and  downloaded the latest build of Baker. We deleted the old app from our Ipad, cleaned the build folder, and then compiled it again.  The Baker app worked but not the index function. 

Then, strangely, we disconnected our Ipad from our Mac and the Baker app worked with the index function! 

So, is my problem with the Ipad device settings or something within the Baker app?

Any advice, suggestions, would be much appreciated. :)

**Comment by folletto** [comment] 2011-09-21 16:24
I have no idea of what could be the cause. Usually after cleaning everything and removing the app on the device it solves any issue, but here seems something related to the launch status.

Maybe: did you try to launch the app keeping it connected but not from Xcode? Something like:
1. Clean everything, remove app from device
2. Run on device
3. Stop the app on Xcode
4. Remove the app from the multitasking bar
5. Launch the app from iPad (without disconnecting it).

This not because I know what it could be, but just to rule out a few possibilities (i.e. that could be related to the connection status).

Did you also try to reboot the device? :)

**Comment by venkatmarri** [comment] 2011-09-22 06:26
I got the same problem... 
I tried to force index size in "index view controller.m"....
define index size "NULL" to 200 or something you wanted.
it should work.

**Comment by dhart23746** [comment] 2011-09-22 11:17
Thanks for the help. 

venkatmarri: I tried your fix and it worked! However, I now get three warnings during the build "Comparison between pointer and integer" on line 207 of "index view controller.m"  Do you think this will be an issue when we submit to Itunes store? 

folletto: I tried to be methodical during the entire build process and keep it as "clean" as possible ... 
1. clean the build folder
2. stop Xcode
3. disconnect the device
4. delete old app
5. reboot
6. Reconnect the device
7. Start Xcode
8. Build app. The app runs on the device but the index didn't work. 

So then I:
1. Stopped Xcode
2. Stopped the app in the multi-task bar
3. Disconnected the device. 
4. Restarted the app ... the index then worked. 

Hope this helps to find the problem.

**Comment by venkatmarri** [comment] 2011-09-22 11:33
Thanks dhart23746:
I used which i mentioned to you.... and submitted to appstore...
its working fine... next time will follow your method...

thanks

**Comment by Simbul** [comment] 2011-09-26 20:24
Nice to know things are working for both of you. Closing the issue.

**Closed as completed by Simbul** 2011-09-26 20:24 UTC
Labels: Discussion
