### ISSUE TITLE
Problem with Vdo fullscreen when Orientation change.

### ISSUE THREAD

**Issue by aspek** [Simbul/baker#514] opened 2012-10-18 08:58 UTC
This is example.How i do it. And got this problem.

1.I use "orientation": "both"

2.I my css 

```
   // in portrait
       .bg{background-image:url(.......)};
       .boxcontent{display:none}

  // in landscape
         .bg{display:none};
         .boxcontent{margin:0; padding:0;}
```

3.In my html use basic tag video
/       <div class= "boxcontent"> <video .....> </video> </div>

Now, When I play vdo and change it to full screen. Try to rotate and exit vdo full screen.Html still show display in landscape mode. How to solved it.

in iOS5 it work perfectly. But not working on iOS6

**Comment by folletto** [comment] 2012-10-18 09:01
Closed because it's a duplicate of #513. Please use that thread. ;)

**Closed as completed by folletto** 2012-10-18 09:01 UTC
