### ISSUE TITLE
Crash when going back to shelf view.

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#574] opened 2012-12-06 05:40 UTC
Here is the scenario.

1)  Open shelf.
2)  Read a downloaded book.
3)  Click on a link in the book that opens up the modal web viewer.
4)  Click Back on the modal web viewer to close it.
5)  Without doing anything else, double tap on the book page to bring up the index and navigation.
6)  Select "Back to Baker Shelf"
7)  Crash

**Comment by nin9creative** [comment] 2012-12-06 05:42
Looks like it's on the dealloc of myModalViewController in BakerViewController.m

 [myModalViewController release];

**Comment by Simbul** [comment] 2012-12-06 22:26
Looks like the issue is still there, only a bit sneakier (and very likely connected to #578):
1. Open shelf.
2. Read a downloaded book.
3. Click on a link in the book that opens up the modal web viewer.
4. Click Back on the modal web viewer to close it.
5. Without doing anything else, double tap on the book page to bring up the index and navigation ~~(index bar is missing)~~.
6. ~~Rotate the device: index bar reappears~~
7. Select "Back to Baker Shelf"
8. Crash

**Comment by ghost** [comment] 2013-01-23 13:05
Has anything come about with this bug yet? Is anyone else having this issue still?
Thank you

**Comment by Simbul** [comment] 2013-01-29 00:19
Looks like we have a related issue:
1. Open shelf
2. Read downloaded book
3. Select "Back to Baker Shelf"
4. Read the same book again
5. Select "Back to Baker Shelf"
6. Crash

**Comment by Simbul** [comment] 2013-01-29 00:27
Ok, the commit above should have fixed the related issue I mentioned.

The previous, "sneakier" issue is still there, though.

**Comment by ghost** [comment] 2013-01-29 13:15
Yep I'm still getting the sneakier crash issue too.
Thanks for your hard work.

**Comment by wwarder** [comment] 2013-02-02 15:53
Thanks for the crash fix. It works!
But I'm still missing the index :(

Open shelf.
Read a downloaded book.
Click on a link in the book that opens up the modal web viewer.
Click Back on the modal web viewer to close it.
Without doing anything else, double tap on the book page to bring up the index (index bar is missing).

UPD: Fixed using https://github.com/Simbul/baker/commit/9d1f8d085a1aba83feeaded9a41a4c44bf453635

**Comment by folletto** [comment] 2013-02-03 19:50
Just to make sure: what are we still missing here? @waywalker does your fix clear all the remaining problems? :)

**Comment by buildc0de** [comment] 2013-02-03 21:54
My fix does seem to clear the remaining "sneakier" crash :-) I don't think there are any other outstanding problems for this specific issue.

**Closed as completed** 2013-02-04 22:11 UTC
Labels: Bug
