### ISSUE TITLE
Jump to mailto: link (and external link in Baker 4.0) causes TOC stop appearing

### ISSUE THREAD

**Issue by calaba** [Simbul/baker#705] opened 2013-02-13 07:27 UTC
Hello,

originally I found the issue on Baker 4.0 code line:
- if using ?Referrer=Baker (or ?Referrer=Safari) in external links - after coming back from the Modal View (or Safari) the TOC stopped appearing ... thus TOC navigation was not further possible

(according to issue https://github.com/Simbul/baker/issues/338 ... which describes similar problems - this supposed to be solved prior Baker 4.0) .. anyway ...)

I tested the problem with latest git code line (from Feb 12th 2013) and there this problems looks to be solved ... !!! BUT !!! in current code line (Feb 12th 2013)

1) if instead of http: link I used mailto: links in the book - the problem still persists - after coming back from email app (both cancel/send buttons) -> the TOC stops appearing.

2) further more - if I used Modal View (Referrer=Baker) and http links and I use back button -> then I am back at the place where I initiated the jump in the book - this is nice feature. But for mailto: links my book chapter is rerenderred and begining of chapter is displayed -> so the reader looses focus and he needs to find back the place where he jumped to the mailto: link to be able to continue reading .... :( not nice - bothering ...

Ric.

**Comment by folletto** [comment] 2013-02-13 10:16
Thanks for the feedback, we'll look into it. :)

**Comment by calaba** [comment] 2013-02-13 22:53
Cool, I am not iOS experienced developer but have some decades of dev. experience so if anyone can point me to the patch which actually solved the issue with "http: link jump" maybe I can try to figure out the correction for mailto: links ... :)

**Comment by folletto** [comment] 2013-02-13 23:38
It was #343. :)

**Comment by buildc0de** [comment] 2013-02-16 22:04
@calaba, just to clarify, when you say "TOC", do you mean the Index View? :-) If yes, then it was 9d1f8d0 (issue #578) that recently dealt with this issue for modal views.

I am able to reproduce on the iPhone, but not on the iPad. That is what you are seeing as well, correct?

**Comment by buildc0de** [comment] 2013-02-16 23:31
The Index View issue is due to a duplicate observer for "notification_touch_intercepted" in -viewWillAppear. Can be resolved by moving addObserver to -viewDidLoad or adding removeObserver before addObserver. 

Will also look into the second issue (preserving the current position) and submit a pull request.

**Comment by calaba** [comment] 2013-02-17 01:46
@waywalker : 

> I am able to reproduce on the iPhone, but not on the iPad. That is what you are seeing as well, correct?

Yes, I observed the problem on iPhone (device and simulator) - didn't try iPad yet.

> when you say "TOC", do you mean the Index View?

Yes, TOC = Index View

**Comment by Xm4s** [comment] 2013-03-05 00:37
I should have fixed the problem with commit 457a888da0a23c579df6626c81c87ea42e7a33ad but I'd like you to test it before closing this issue up

**Comment by buildc0de** [comment] 2013-03-08 01:11
Oh, I see! :-)
Yep, makes more sense to do it that way. However, the fix appears to be incomplete. Currently, it relies on "currentPageWillAppearUnderModal = YES" being set in -closeModalWebView, but we are coming back from MFMailComposeViewController ;-) But adding the line below appears to fix the issue completely:

```
[mailer release];
currentPageWillAppearUnderModal = YES;
```

**Comment by buildc0de** [comment] 2013-03-08 01:18
Just checked the master and the line is already there. Must've been implemented while I wasn't looking! :) So it's all good, this can be closed.

**Closed as completed** 2013-03-11 22:03 UTC
Labels: Bug, Waiting follow-up
