### ISSUE TITLE
Error loading Shelf manifest: Error Domain=NSCocoaErrorDomain Code=256

### ISSUE THREAD

**Issue by aasheaa** [Simbul/baker#601] opened 2012-12-27 03:36 UTC
2012-12-27 10:56:13.555 Baker[1038:1a303] ====== Newsstand is enabled ======
2012-12-27 10:56:13.561 Baker[1038:1a303] Error loading Shelf manifest: Error Domain=NSCocoaErrorDomain Code=256 "The operation couldn’t be completed. (Cocoa error 256.)" UserInfo=0x952ae10 {NSURL=}
2012-12-27 10:56:13.562 Baker[1038:1a303] No cached Shelf manifest found at /Users/wangyan/Library/Application Support/iPhone Simulator/6.0/Applications/3F9DD602-03F5-4D8E-8F61-F9E565D4D5C2/Library/Caches/shelf.json
2012-12-27 10:56:13.571 Baker[1038:1a303] Subscription not enabled: constant PRODUCT_ID_FREE_SUBSCRIPTION not set
2012-12-27 10:56:13.575 Baker[1038:1a303] Error loading Shelf manifest: Error Domain=NSCocoaErrorDomain Code=256 "The operation couldn’t be completed. (Cocoa error 256.)" UserInfo=0xa54fd40 {NSURL=}
2012-12-27 10:56:13.575 Baker[1038:1a303] No cached Shelf manifest found at /Users/wangyan/Library/Application Support/iPhone Simulator/6.0/Applications/3F9DD602-03F5-4D8E-8F61-F9E565D4D5C2/Library/Caches/shelf.json
ççç

**Comment by folletto** [comment] 2012-12-27 03:53
Duplicate of Issue #600. Closing. Please continue on the other one. :)

**Closed as completed by folletto** 2012-12-27 03:53 UTC
