### ISSUE TITLE
Buy button doesn't change to Download

### ISSUE THREAD

**Issue by callaght** [Simbul/baker#1044] opened 2013-07-24 06:39 UTC
Just using the latest Master and I noticed the Buy button doesn't change to Download once a successfull purchase has been made.

This is how the button looks when I execute Baker

![screen shot 2013-07-22 at 17 56 48](https://f.cloud.github.com/assets/4885291/846915/1f6e8bec-f42b-11e2-8a6e-1497c216f966.png)

If I tap the Buy button I go through the purchasing process: -

![screen shot 2013-07-24 at 07 34 54](https://f.cloud.github.com/assets/4885291/846917/434e1244-f42b-11e2-91c8-40904cad4e62.png)
![screen shot 2013-07-24 at 07 35 04](https://f.cloud.github.com/assets/4885291/846923/4e64c86c-f42b-11e2-92a0-86b8c49aa991.png)

Then once complete the button still looks like this: -

![screen shot 2013-07-22 at 17 56 48](https://f.cloud.github.com/assets/4885291/846927/6b19f2ca-f42b-11e2-9f61-5f7a7af59514.png)

But if I tap the Buy button now it'll start downloading the magazine: -

![screen shot 2013-07-24 at 07 35 27](https://f.cloud.github.com/assets/4885291/846931/8460157a-f42b-11e2-8eea-f7104b89b002.png)

So its as if everything works correctly, but the Buy button doesn't change to Download.  Is it something maybe I have configured incorrectly?

**Comment by folletto** [comment] 2013-07-24 13:21
As usual, the first I have to ask you to go through [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) and report back :)

**Comment by freney** [comment] 2013-07-24 13:21
If you scroll that issue off screen and then back on again (so that the button re-draws) does it change to what it should be?

If so, then that's a duplicate of a bug I encountered, which I think is because of the way that the UICollectionView handles refreshing and redrawing. I had it in my app, but I figured it was because of some of the weird mods I made.

**Comment by callaght** [comment] 2013-07-26 08:45
Thanks for your suggestion freney.  I have scrolled off and on screen again on simulator but the button doesn't re-draw.

I've got an iPad Mini now but due to the Developer Portal being down I can't provision it as a development device.

I've no idea how long the Apple Dev Portal is going to be down (1 week so far) so, I've gone ahead and submitted it for review with Apple.

If it get's approved, that'll be the next time I can test it on a real device.

My fingers are crossed :-)

**Comment by callaght** [comment] 2013-07-27 23:14
Unfortunately just received a rejection from Apple a few minutes ago.

Slapshot Mag got rejected by Apple because the Buy button did not update to a Download button.

This is what they said in the Resolution Center:

> We found that your app exhibited one or more bugs, when reviewed on iPad running iOS 6.1.3, on both Wi-Fi and cellular networks, which is not in compliance with the App Store Review Guidelines.
> 
> After purchasing a Subscription, the magazine does not become available for download.

This is the screenshot they provided: -

![screen shot 2013-07-28 at 00 13 14](https://f.cloud.github.com/assets/4885291/867615/2867b7ca-f712-11e2-822c-3d0d4f072425.png)

If only they knew they could just tap that button again and it would download!! :-(

Does anyone know of a fix for the Buy button not updating to Download issue?

Seems fine on the current 4.1, but not on the Master.

**Comment by folletto** [comment] 2013-07-27 23:25
Could you please go through [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) and report back? Without that information is difficult to help you. :)

**Comment by folletto** [comment] 2013-07-27 23:27
Also: note that Apple says:

> After purchasing a Subscription, the magazine does not become available for download.

It's telling you a problem with **Subscriptions**, not individual purchases. That might be a completely different issue.

**Comment by callaght** [comment] 2013-07-28 18:13
I think you could be right and maybe I have misunderstood the reason for the app rejection.

For the past 2 submissions to the AppStore that I have been rejected for I have struggled to understand what is required of the subscription In-App purchase Display Name and Description.

For the 3 month subscription with 30 days free trial, I have tried: -

Display Name: 1 Month FREE trial
Description:  1 Month FREE trial

Rejected.  When I looked up what is required for the Display Name, iTunes Connect help says: -

> This is the name of the In-App Purchase that will be seen by customers (if this is their default language). For auto-renewable subscriptions, do not include a duration in the display name. The display name cannot be longer than 75 bytes.

For description, help says: -

> This is the description of the In-App Purchase that will be used by App Review during the review process. If indicated in your code, this description may also be seen by customers. For auto-renewable subscriptions, do not include a duration in the description. The description cannot be longer than 255 bytes.

So based on this, I re-submitted with: -

Display Name: Slapshot
Description:  Slapshot

All of my In-Apps got rejected again - one off purchase, 3 months auto-renewable with 30 free trial and 6 month auto-renewable subscription.

![screen shot 2013-07-28 at 19 05 28](https://f.cloud.github.com/assets/4885291/868599/46c31df0-f7b1-11e2-9bdd-28fb5976723f.png)

![screen shot 2013-07-28 at 19 06 09](https://f.cloud.github.com/assets/4885291/868600/4ec1f0f8-f7b1-11e2-874c-0e529647622a.png)

![screen shot 2013-07-28 at 19 06 28](https://f.cloud.github.com/assets/4885291/868601/5606b0b0-f7b1-11e2-93bb-8bd805fba8a4.png)

What do I put?  I have absolutely no idea!

Maybe this is the key to resolving the whole thing?

**Comment by callaght** [comment] 2013-07-29 14:57
I've been looking at how other magazines have described their subscriptions: -

![photo 1](https://f.cloud.github.com/assets/4885291/872250/ff7a9514-f85e-11e2-9a29-dc5d5dca6c50.PNG)

![photo 2](https://f.cloud.github.com/assets/4885291/872253/0ecb4ba8-f85f-11e2-9d90-ddb022f0eb38.PNG)

How do those translate into the In-App purchase subscription 'Display Name' and 'Description' in iTunes Connect?

**Comment by freney** [comment] 2013-07-29 21:26
That's a StoreKit dialog that you cannot change in anyway. It will always say:

"Do you want to subscribe to <TITLE> for <DURATION> for <PRICE>? This subscription will automatically renew until canceled."

Which means, amongst other things, you need to give it a title that makes sense in that sentence.

**Closed as completed** 2013-07-29 22:03 UTC
Labels: Support, Investigation Required

**Comment by Simbul** [comment] 2013-07-29 22:07
The issue with the BUY/DOWNLOAD button was indeed a bug, which should be fixed in the latest master.

I've closed the thread as the issue has been fixed. Please open a new one if you are still struggling with subscriptions.

**Comment by callaght** [comment] 2013-07-30 08:31
Thank you! :-)
