### ISSUE TITLE
Eliminate page number, spinner and white flash between pages?

### ISSUE THREAD

**Issue by MacBoy** [Simbul/baker#40] opened 2011-01-10 15:26 UTC
is there a technical reason for delaying the display of the next page?

Could a simple slide-left transition be used in place of the page numbering, white flash and spinner?

For most usage (book, magazine, catalog), I cannot envision a need for inserting that stuff in between the pages.  It simply gets in the way and it is awkward.  Each time, I have to apologize and explain to our users.

Perhaps make it be optional?  Enable it within the plist.

**Comment by folletto** [comment] 2011-01-10 15:31
Could you point out where? We **don't add any delay**, just the time needed for the page to scroll: the page loading is delayed exactly by the time it takes to scroll.
If we fire the two events at the same time the scroll will stutter, creating an even more unpleasant effect (in the worst scenario, it doesn't even show the scroll animation, it just replaces the page after a blank screen).

**Comment by folletto** [comment] 2011-01-31 16:30
I'll mark this as duplicate of issue #27

**Closed as completed by folletto** 2011-01-31 16:30 UTC
