### ISSUE TITLE
Error while double tap with two finger 

### ISSUE THREAD

**Issue by ahmetomer** [Simbul/baker#464] opened 2012-08-14 07:47 UTC
Hi all,

 I'm working first Baker app and I have a problem.  When double tab to screen with double finger baker lock the scroll (not always most of the time) and error is;

Ignoring call to [UIPanGestureRecognizer setTranslation:inView:] since gesture recognizer is not active.

Is this a known issue or any idea ?

Thanks

**Comment by folletto** [comment] 2012-08-15 17:14
We weren't aware of it, we'll check. Thanks. :)

**Comment by Simbul** [comment] 2012-08-20 20:56
Hello @ahmetomer, I'm sorry but I could not reproduce the issue on my iPad.

Which version of Baker are you running? Is it the `master` branch on https://github.com/Simbul/baker ?

**Comment by folletto** [comment] 2012-09-03 19:29
Do you have any update @ahmetomer? Otherwise we'll close this issue...

**Closed as completed** 2012-09-09 13:58 UTC
