### ISSUE TITLE
Ghost screenshot after switch to external book and back

### ISSUE THREAD

**Issue by zenz** [Simbul/baker#229] opened 2011-12-07 03:09 UTC
was: book://local problem again

all right, another problem.

If I switch back to bundle book with book://local, it seems all right. but if I completely close(kill) the baker program. then open it again, it will just show the one which was reading before bundle book.

I think it's a mistake handling?

**Comment by zenz** [comment] 2011-12-07 03:12
And also there's a problem may be belongs to this issue.

While switch to bundle book for reading, while swipe to the page which was the previous book closed. it will show the screenshot of that page, but not the bundle books screenshot.

Please check.

**Comment by Xm4s** [comment] 2011-12-09 00:23
Ok, I've seen the problems with the screenshot, (which is kinda funny, since that screenshot is deleted as soon as the downloaded book is closed) ... I'll look into it.

About the switching of books on application kills, I wasn't able to reproduce the bug.
Maybe it's related to the other issue you have opend on book://local, so let's start understanding that.

**Comment by zenz** [comment] 2011-12-09 01:25
Hi, Xm4s.

Is that book://local designed only for internal open bundle book?

**Comment by zenz** [comment] 2011-12-09 02:33
I re-clone the newest source code of baker from github and do the test. it's the same. while I switch back to bundle book with book://local. and then completely kill baker, and then run it again. it will just show the previous book.

**Comment by Xm4s** [comment] 2011-12-10 11:44
I've detailed the steps I made to test switching from a bundled book to a downloaded one on issue #232
We should continue our discussion about that there while leaving this issue dedicated to the "ghost screenshot from book://local".

By the way thank you for finding that out :)

**Comment by zenz** [comment] 2011-12-12 01:04
I confirmed that with git version c63423662974, baker have the above bug. but with the newest version which have apple iCloud patch fix the problem.
great work! Xm4s!!!

Please fix the ghost screenshot next. :)

**Comment by Xm4s** [comment] 2012-04-03 22:34
Actually turned out that the ghost screenshot was instead a remains of the previous book last page :)
This was fixed with the commit fa415eeb17013904de48c66aef9d9cf26e1ca933

**Closed as completed by Xm4s** 2012-04-03 22:34 UTC
Labels: Bug
