### ISSUE TITLE
Help... Baker keeps crashing

### ISSUE THREAD

**Issue by teamstar** [Simbul/baker#253] opened 2011-12-25 17:49 UTC
Hi guys...
After upgrading to baker v3(and just figured out about json.book in the v3 edition), my app keeps crashing...
Is it something to do with my json file?

Here's my json file:

```
{
    "hpub": 1,
    "title": "PSLE Math Revealed v1.5",
    "author": "Joe Shamuraq",
    "creator": ["Joe Shamuraq"],
    "publisher": "Neutrino Paradigm Pte Ltd",
    "date": "2011-08-23",
    "url": "book://neutrinoparadigm.com/books/psle-math-revealedv1.5",

    "orientation": "both",
    "zoomable": false,

    "contents": [
    "cover01.html",
    "cover02.html",
    "cover03.html",
    "cover04.html",
    "topic01_01.html",
    "topic01_02.html",
    "topic01_03.html",
    "topic01_04.html",
    "topic01_05.html",
    "topic01_06.html",
    "topic01_07.html",
    "topic01_08.html",
    "topic01_09.html",
    "topic01_10.html",
    "topic01_11.html",
    "topic01_12.html",
    "topic01_13.html",
    "topic01_14.html",
    "topic01_15.html",
    "topic01_16.html",
    "topic01_17.html",
    "topic01_18.html",
    "topic01_19.html",
    "topic01_20.html",
    "topic01_21.html",
    "topic01_22.html",
    "topic01_23.html",
    "topic01_24.html",
    "topic02_01.html",
    "topic02_02.html",
    "topic02_03.html",
    "topic02_04.html",
    "topic02_05.html",
    "topic02_06.html",
    "topic02_07.html",
    "topic02_08.html",
    "topic02_09.html",
    "topic02_10.html",
    "topic02_11.html",
    "topic02_12.html",
    "topic02_13.html",
    "topic02_14.html",
    "topic02_15.html",
    "topic02_16.html",
    "topic02_17.html",
    "topic02_18.html",
    "topic02_19.html",
    "topic02_20.html",
    "topic02_21.html",
    "topic02_22.html",
    "topic02_23.html",
    "topic02_24.html",
    "topic02_25.html",
    "topic02_26.html",
    "topic02_27.html",
    "topic02_28.html",
    "topic02_29.html",
    "topic02_30.html",
    "topic02_31.html",
    "topic02_32.html",
    "topic02_33.html",
    "topic02_34.html",
    "topic02_35.html",
    "topic02_36.html",
    "topic02_37.html",
    "topic02_38.html",
    "topic02_39.html",
    "topic02_40.html",
    "topic02_41.html",
    "topic02_42.html",
    "topic02_43.html",
    "topic02_44.html",
    "topic02_45.html",
    "topic02_46.html",
    "topic02_47.html",
    "topic02_48.html",
    "topic02_49.html",
    "topic02_50.html",
    "topic02_51.html",
    "topic02_52.html",
    "topic03_01.html",
    "topic03_02.html",
    "topic03_03.html",
    "topic03_04.html",
    "topic03_05.html",
    "topic03_06.html",
    "topic03_07.html",
    "topic03_08.html",
    "topic03_09.html",
    "topic03_10.html",
    "topic03_11.html",
    "topic03_12.html",
    "topic03_13.html",
    "topic03_14.html",
    "topic03_15.html",
    "topic04_01.html",
    "topic04_02.html",
    "topic04_03.html",
    "topic04_04.html",
    "topic04_05.html",
    "topic04_06.html",
    "topic04_07.html",
    "topic04_08.html",
    "topic04_09.html",
    "topic04_10.html",
    "topic04_11.html",
    "topic04_12.html",
    "topic04_13.html",
    "topic04_14.html",
    "topic04_15.html",
    "topic04_16.html",
    "topic04_17.html",
    "topic04_18.html",
    "topic04_19.html",
    "topic04_20.html",
    "topic04_21.html",
    "topic04_22.html",
    "topic04_23.html",
    "topic04_24.html",
    "topic04_25.html",
    "topic04_26.html",
    "topic04_27.html",
    "topic04_28.html",
    "topic04_29.html",
    "topic04_30.html",
    "topic04_31.html",
    "topic04_32.html",
    "topic04_33.html",
    "topic04_34.html",
    "topic04_35.html",
    "topic04_36.html",
    "topic04_37.html",
    "topic05_01.html",
    "topic05_02.html",
    "topic05_03.html",
    "topic05_04.html",
    "topic05_05.html",
    "topic05_06.html",
    "topic05_07.html",
    "topic05_08.html",
    "topic05_09.html",
    "topic05_10.html",
    "topic05_11.html",
    "topic05_12.html",
    "topic05_13.html",
    "topic05_14.html",
    "topic05_15.html",
    "topic05_16.html",
    "topic05_17.html",
    "topic05_18.html",
    "topic05_19.html",
    "topic05_20.html",
    "topic05_21.html",
    "topic05_22.html",
    "topic06_01.html",
    "topic06_02.html",
    "topic06_03.html",
    "topic06_04.html",
    "topic06_05.html",
    "topic06_06.html",
    "topic06_07.html",
    "topic06_08.html",
    "topic06_09.html",
    "topic06_10.html",
    "topic06_11.html",
    "topic06_12.html",
    "topic06_13.html",
    "topic06_14.html",
    "topic06_15.html",
    "topic06_16.html",
    "topic06_17.html",
    "topic06_18.html",
    "topic06_19.html",
    "topic06_20.html",
    "topic06_21.html",
    "topic06_22.html",
    "topic06_23.html",
    "topic06_24.html",
    "topic06_25.html",
    "topic07_01.html",
    "topic07_02.html",
    "topic07_03.html",
    "topic07_04.html",
    "topic07_05.html",
    "topic07_06.html",
    "topic07_07.html",
    "topic07_08.html",
    "topic07_09.html",
    "topic07_10.html",
    "topic07_11.html",
    "topic07_12.html",
    "topic07_13.html",
    "topic07_14.html",
    "topic07_15.html",
    "topic07_16.html",
    "topic07_17.html",
    "topic07_18.html",
    "topic07_19.html",
    "topic07_20.html",
    "topic07_21.html",
    "topic07_22.html",
    "topic07_23.html",
    "topic07_24.html",
    "topic07_25.html",
    "topic07_26.html",
    "topic07_27.html",
    "topic08_01.html",
    "topic08_02.html",
    "topic08_03.html",
    "topic08_04.html",
    "topic08_05.html",
    "topic08_06.html",
    "topic08_07.html",
    "topic08_08.html",
    "topic08_09.html",
    "topic08_10.html",
    "topic08_11.html",
    "topic08_12.html",
    "topic08_13.html",
    "topic08_14.html",
    "topic08_15.html",
    "topic08_16.html",
    "topic08_17.html",
    "topic08_18.html",
    "topic08_19.html",
    "topic08_20.html",
    "topic08_21.html",
    "topic08_22.html",
    "topic08_23.html",
    "topic08_24.html",
    "topic08_25.html",
    "topic08_26.html",
    "topic08_27.html",
    "topic08_28.html",
    "topic08_29.html",
    "topic08_30.html",
    "topic08_31.html",
    "topic08_32.html",
    "topic08_33.html",
    "topic08_34.html",
    "topic08_35.html",
    "topic08_36.html",
    "topic08_37.html",
    "topic08_38.html",
    "topic08_39.html",
    "topic08_40.html",
    "topic09_01.html",
    "topic09_02.html",
    "topic09_03.html",
    "topic09_04.html",
    "topic09_05.html",
    "topic09_06.html",
    "topic09_07.html",
    "topic09_08.html",
    "topic09_09.html",
    "topic09_10.html",
    "topic09_11.html",
    "topic09_12.html",
    "topic09_13.html",
    "topic09_14.html",
    "topic09_15.html",
    "topic10_01.html",
    "topic10_02.html",
    "topic10_03.html",
    "topic10_04.html",
    "topic10_05.html",
    "topic10_06.html",
    "topic10_07.html",
    "topic10_08.html",
    "topic10_09.html",
    "topic10_10.html",
    "topic10_11.html",
    "topic10_12.html",
    "topic10_13.html",
    "topic10_14.html",
    "topic10_15.html",
    "topic10_16.html",
    "topic10_17.html",
    "topic10_18.html",
    "topic10_19.html",
    "topic10_20.html",
    "topic10_21.html",
    "topic10_22.html",
    "topic10_23.html",
    "topic10_24.html",
    "topic10_25.html",
    "topic10_26.html",
    "topic11_01.html"
  ]
}
```

**Comment by zenz** [comment] 2011-12-26 02:12
you should check the log.

**Comment by teamstar** [comment] 2011-12-26 05:11
I'm really a newbie which is why i opted for a ready framework.How do i check the log? Is it in the iPad or Mac where my Xcode is?

**Comment by mutador** [comment] 2011-12-26 10:35
your book looks too much big fot screenshoot , why you don´t try three cards? in render mode   (    "-baker-rendering": "three-cards"), and update your  json file , whit the new references 3.1

  {
    "-baker-background": "#000000",
    "-baker-vertical-bounce": true,
    "-baker-index-height": 150,
    "-baker-index-bounce": true,
    "-baker-media-autoplay": true,
    "-baker-background-image-portrait": "assets/background-portrait.png",
    "-baker-background-image-landscape": "assets/background-landscape.png",
    "-baker-page-numbers-color": "#FFFFFF",
    "-baker-page-numbers-alpha": 0.5,
    "-baker-vertical-pagination": false,
    "-baker-rendering": "three-cards"
  }

**Comment by teamstar** [comment] 2011-12-26 15:05
how does the new json reference 3.1 look like? I tried to look for v3.1 tutorial but tutorial only covers for up to 3.0... Please help :(

**Comment by mutador** [comment] 2011-12-26 15:29
you must download the last code  https://github.com/Simbul/baker and see the reference http://bakerframework.com/tutorials/30/manifest#baker-properties

Using Baker specific properties

In addition to the properties from the HPub specification, Baker supports its own set of properties. All the properties, which are optional, are shown in the following examples (as above, note that this is not a valid manifest):

-baker-rendering
Rendering mode to use for the publication. As a rule of thumb, heavier publications will benefit from the "screenshots" rendering, while highly interactive publications will require the "three-cards" rendering.

 {
  "-baker-rendering": "three-cards"

---

but , what happend when you say crashing.... when you load a especific page?, when you rotatae? when load 30 pages or more? in a video page?

**Comment by Simbul** [comment] 2012-02-06 22:24
Hi @teamstar, have you managed to sort this out in the end?

**Comment by folletto** [comment] 2012-02-14 00:32
I'm cleaning up the issue tracker, so I'm closing this issue. If the problem is still there, please feel fee to re-open this. :)

**Closed as completed by folletto** 2012-02-14 00:32 UTC
