### ISSUE TITLE
Issue with index page

### ISSUE THREAD

**Issue by MaverickWar** [Simbul/baker#948] opened 2013-06-08 22:29 UTC
On my index page im getting parts of the document showing at the top of the screen and im not sure why, its the same on every page...
![issue with top](https://f.cloud.github.com/assets/4552051/628208/d0804c46-d08a-11e2-8d40-b1e1eecd1b92.png)

**Comment by folletto** [comment] 2013-06-08 23:46
I'm not sure what you're asking. What are you trying to do?

The index is something you build: the covered area is up to you.

**Comment by MaverickWar** [comment] 2013-06-08 23:53
well can understand why the image file is showing the logo at the top of the slide, when i view it in a browser, it displays as a slider, this is what it should be, in a mobile device, it brings some sort of issue at the top, if you look at the image above, above the slide images there is parts of the blue logo coming through, but this isnt in the index file....

Im referring to the blue bar under the revuitnet black bar and above the slides on index.

**Comment by folletto** [comment] 2013-06-08 23:57
It's very difficult to tell what's going on without the HTML. If you're sure that the `index.html` covers the full height of the page, then the only other thing that comes in my mind is that maybe the background isn't set. 
By default the index is transparent.

Notice also that a wider index will natively scroll without the need of any javascript or library.

**Comment by MaverickWar** [comment] 2013-06-09 00:13
which background could be set to transparent? also where do i check hight is fully covered?

**Comment by MaverickWar** [comment] 2013-06-09 00:17
This is the index html im using.

http://pastebin.com/82WtmKLY

**Comment by folletto** [comment] 2013-06-09 00:19
The 'index.html' body is by default transparent. Set a color to it. Maybe set red at first so you can see if it covers all or not ;)

I can't tell from the HTML without the CSS loaded into it. Also: you don't need any JavaScript.

**Comment by MaverickWar** [comment] 2013-06-09 00:34
Still doesnt work with background changed, it was set to white....

![redindex](https://f.cloud.github.com/assets/4552051/628332/5099c694-d09c-11e2-9bf9-2b2abcbdb735.png)

**Comment by folletto** [comment] 2013-06-09 00:35
See? That means that the index is shorter than the page. Make it higher. :)

Or we'll, shorter. The solution you're using feels better if it covers just the bottom part of the screen, so having it as high as the thumbnail,

**Comment by MaverickWar** [comment] 2013-06-09 00:51
I tried this but page height is set to 100%.... the only thing i can think of is that i used IN5 demo to export the index file and i edited the links, maybe the demo version breaks this file slightly for use on production?

**Comment by folletto** [comment] 2013-06-09 14:44
Baker sizes the index as the size you specify: so "height: 100%" means just that it's 100% of the content you have on the HTML page, not 100% of the screen. That's how HTML works. :)

**Comment by MaverickWar** [comment] 2013-06-09 14:50
Ok, we'll I'm relatively new to all this... Does the mean I'm looking for a setting in baker for size or am I looking in the HTML?

Sorry if this is an easy noob question but my brain is a little fried aswell today, had a late night last night playing around with all this.

**Comment by folletto** [comment] 2013-06-09 14:52
Everything is in the HTML. If the page size (i.e. the red area you see above) is smaller than the screen, Baker will create an index smaller than the screen. All HTML. :)

**Comment by MaverickWar** [comment] 2013-06-09 14:56
Ok I'm slowly getting there, the complicated bit from my side is I use in5 locked down demo to create the index, then I use hype to create the individual pages and I open the index file generated by the in5 demo in dream weaver and link the thumbnails to the hype created pages...

Not sure what I would do to fix the index as its exported and created via a cripples demo of in5.

Do you have any steps that might help? If I can fix the index issue then I will be sorted.

**Comment by nin9creative** [comment] 2013-06-09 15:04
Yeah, but it's just HTML right?  The index I would imagine is pretty simple.  Especially generated from in5, it's just setting up a row of image previews from the pages
in the document and linking them to the pages.  I'm sure it would be fairly straightforward to edit and tweak however you want.

**Comment by MaverickWar** [comment] 2013-06-09 15:08
That's what I thought, but I've tried setting all settings I can think off to 100% height in order to get a proper index page, I keep thinking the in5 demo is adding some weird formatting or a little bug as its not a full version, I've removed the in5 footer bar from the index page aswell to see if that caused it, I got right down to just index page and thumbnails and still it's not right. I know I'm probably missing easy... But I just can't see it, code itself is basic and the issue does not show in design view on dream weaver, it only shows when compiled and viewed on device

**Comment by MaverickWar** [comment] 2013-06-09 15:09
Is there a viewport code for height aswell as width? There appears to be a bit of code with viewport relating to width but not height

**Comment by MaverickWar** [comment] 2013-06-09 15:11
I may just grab the laker index soon and edit that if this doesn't work

**Comment by folletto** [comment] 2013-06-09 15:33
As said: it's all in the HTML/CSS. If it doesn't work, check the sizes in the box model of the HTML you're using. It's all there. Don't check Baker for that, you'll just spend time down a wrong path: all it does is reading the page height and positioning the page at the bottom of the screen. It's all in the HTML/CSS.

**Comment by marcheluis** [comment] 2013-06-13 01:13
actually, isn't there an option in the book.jsonlike "-baker-index-height"?

**Comment by folletto** [comment] 2013-06-13 10:04
Precisely: https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters ;)
While it's mostly a fallback, worth a try. ;)

**Comment by Simbul** [comment] 2013-06-24 21:01
Have you managed to solve this issue?

**Comment by justinputney** [comment] 2013-09-03 22:38
The issue with arrows appearing on the index page has been fixed with an update to in5. The rest of what I'm seeing in the posts above looks like expected behavior.

The index page isn't necessary meant to function as a standalone, it's used by Baker to show thumbnails for each page when the user double taps. And in5 links each thumbnail to the corresponding page by default.

**Comment by MaverickWar** [comment] 2013-09-03 23:53
So how do I make this look right because clearly that looks stupid?

**Comment by justinputney** [comment] 2013-09-04 15:53
Can you create a visual mockup of how you would like it to look? Then I can tell you if/how you can create it...

**Comment by folletto** [comment] 2013-11-15 11:28
I'm closing this issue due to the lack of feedback. If there's any follow-up we'll re-open it. :)

**Closed as completed by folletto** 2013-11-15 11:28 UTC
Labels: Support

**Comment by jhmac** [comment] 2013-11-17 12:28
I had a similar problem and fixed it with adding a height to viewport.
Yours : -  meta name="viewport" content="width=device-width"
mine:  - meta name="viewport" content="width=5775 height=135"
this got the my content to the bottom of the page.
