### ISSUE TITLE
App crash when unzipping / in some time

### ISSUE THREAD

**Issue by aspek** [Simbul/baker#766] opened 2013-03-15 08:13 UTC
I have big problem. But am not good in English. I will Explain by image.
Hope you can understand this.

![simple](https://f.cloud.github.com/assets/2587452/262713/f11ad08e-8d46-11e2-8556-972256c4086e.jpg)

**Comment by folletto** [comment] 2013-03-15 18:37
If it crashes during the unzip process it's likely it's not able to clean-up the temporary file, so that might be the reason of the final size you show.

That said, please follow the instructions on [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) and if it doesn't work paste here the information specified there. :)

**Comment by Simbul** [comment] 2013-03-15 19:26
This is definitely the best issue I've seen so far! :D Great way of overcoming linguistic barriers.

A possibility is that 200Mb is a bit too much for the zip library or the device. Have you tried with smaller files (e.g. 150Mb, 100Mb, 50Mb...)?

As for the reason for the trash file, I think @folletto is right.

**Comment by aspek** [comment] 2013-03-15 19:56
Yes, I have small book 90mb that is no problem. 
Anyway, I need to use a lot of images(normal&retina) files. Because my clients have requirement "The book can open at anywhere no need wifi".

Is possible. For solving this problem. Such as if delete the book it will find temporary file and remove it together. or check status unzip process if not finish come check temp file and remove it again .

The last words that I spoke well. Thanks you!!.

**Comment by Simbul** [comment] 2013-03-15 22:31
It wouldn't be easy, as we drop the reference to the temporary file as soon as we finish the download.
That space should be marked as temporary, anyway, so the iPad should be able to reclaim it if needed.

Btw, I wasn't able to reproduce the crash when uncompressing, even with a ~700Mb file on an iPad1.

**Comment by aspek** [comment] 2013-03-16 05:43
It is a good reason. I'm going to talk to my boss.
@folletto Thanks, But my case going on iPad4.

**Comment by folletto** [comment] 2013-03-31 17:37
Hello, did you solve this? :)

**Comment by aspek** [comment] 2013-04-01 05:23
I don't know what is best way.
 But I change process when zipping file to "normal " not "better" <-- i use application for zip file. 
And change image  quality to medium for small files/ that i can do. And hope some user not get this problem.HAHA

**Closed as completed** 2013-04-01 14:15 UTC
Labels: Support
