### ISSUE TITLE
Rejected Binary (Issue 2):  No Internet Connection, App Doesn't Handle This

### ISSUE THREAD

**Issue by jbavington** [Simbul/baker#990] opened 2013-07-02 02:19 UTC
Hey crew,

My 2nd issue involving the binary reject was:

When the device is connected to a 3G or Wi-Fi network, your app does not load its contents and stays blank.

Please see the attached screenshot/s for more information.

Please review the Reachability iPhone program code sample that demonstrates the use of the System Configuration Reachability API to detect the absence of Wi-Fi and Wireless Wide Area Network (WWAN) services. Your app can then take appropriate action at the first point where network services are required.
For discrete code-level questions, you may wish to consult with Apple Developer Technical Support. Please be sure to:
- include the complete details of your rejection issues
- prepare any symbolicated crash logs, screenshots, and steps to reproduce the issues for when the DTS engineer follows up.

For information on how to symbolicate and read a crash log, please see Tech Note TN2151 Understanding and Analyzing iPhone OS Application Crash Reports.

While I'm pretty sure they meant to say "When the device is _not_ connected..." in that first sentence, I'm not sure how to proceed with this.  

Below is the screenshot that they sent me:

![no_internet_connect](https://f.cloud.github.com/assets/4700969/734247/b0f0eeb8-e2bd-11e2-95a0-a971aa2fb0da.png)

I'm not a coder, but can stumble around Xcode. 

Assistance gratefully appreciated!

Thanks.

**Comment by folletto** [comment] 2013-07-02 10:08
I'm not sure what to say. There are already lots of magazines published with no issue at all regarding connectivity. I could maybe guess that they really mean "When the device is connected", and something went wrong on the server the moment they tested the app. Maybe just try to resubmit?

**Comment by jbavington** [comment] 2013-07-02 13:11
Hey, thanks.

I found I could reproduce the above issue Apple flagged when running through the iPhone/iPad v6.0 simulator in Xcode.  Sure enough, no connectivity.

Strangely, running it through v5.1 or v6.1 of both the iPhone/iPad simulators does not cause this issue and it connects to the server just fine.

Any thoughts one what I missed or what I can add for v6.0 specifically?

Thanks.

**Comment by benoitchantre** [comment] 2013-07-02 13:45
I can't reproduce it with the original Baker app and iOS Simulator 6.0

Here's the log from Xcode when I click on the refresh button.
There's no alert, unless I try to download an issue.

```
2013-07-02 15:35:16.309 Baker[19701:c07] [ERROR] Failed GET request to http://bakerframework.com/demo/shelf.json?user_id=DF5298C2-942D-4436-A555-9C15AFB4AA3D&app_id=com.yourcompany.Baker: The Internet connection appears to be offline.
2013-07-02 15:35:16.309 Baker[19701:c07] [BakerShelf] Loading cached Shelf manifest from /Users/istory/Library/Application Support/iPhone Simulator/6.0/Applications/8C1621F1-17E5-4CF3-8DA1-C2C6BFF36CA0/Library/Caches/shelf.json
```

You should maybe upgrade you app with the latest code from the master branch.

**Comment by folletto** [comment] 2013-07-02 13:50
@jbavington what's in the logs? Could you please follow the instructions in [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) and report back?

**Comment by jbavington** [comment] 2013-07-02 23:21
ok, well I feel rather silly on this one.  Checking the Xcode logs, it said it couldn't find the JSON file on the server and to check the "NEWSSTAND_MANIFEST_URL" value in Constants.h

I reviewed that and double-checked what I had on the server.  Server was wrong.  'doh!

It works in the simulator now.   HOWEVER, what does the app do if there is NO internet connection?

Thanks.  And back to issue #989  ...

**Comment by folletto** [comment] 2013-07-02 23:35
It does what you posted in the screenshot above. :)

Good then! I'm closing this. :)

**Closed as completed by folletto** 2013-07-02 23:35 UTC
Labels: Support
