### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by creatov** [Simbul/baker#23] opened 2010-11-16 16:00 UTC
Hi guys, love the framework! Finally something that simply works easy without the necessity to dive into the code. Hope someday I will understand that also better. But again, I believe you're the first delivering something just easy. And it's unbelievable it's free. Hope I can contribute to the project somehow, even though I'm not a coder.

I'm trying to setup an e-book/magazine in the framework with proper use of html5. No problemo at all. Hyperlink-navigation is wonderful. Thanks for adding that. Makes it a more interactive experience. There are some issues I see. Hope it helps to make things better:
1. Background is flashing during navigating to the next page. You see a glimpse of page 2 if you navigate to page 3.
2. Now I've 16 html pages in the /book directory. Tab right on page 16 brings me to page 7 and I do not understand why.
3. Tap on the bottom of the page is great to continue reading on the same page. But not when you're almost at the end. Then the animation is strange.

I've just one request that will make this framework complete. Think it's mentioned already. But something for pagenavigation (like TIME Magazine and others using the WoodWing framework or other frameworks) will make this a superwonderful project.

Thanks for helping me out!

**Comment by Xm4s** [comment] 2010-11-16 19:37
Hi creatov!

Thank you for your praising words! We are always happy to find someone who likes Baker. Also, thank you for opening this issue as well, we always need feedbacks on the framework to fix and improve it, so you are already helping us here :)

Now lets see your points:
1. If I've understand correctly you are referring at the white background with page numbers that could be seen while jumping from nonconsecutive pages. At this time that is the expect behaviour of the framework and it's a way to show the reader that he has moved backward/forward in the navigation of the book; However we are already discussing other solutions about the background in this issue https://github.com/Simbul/baker/issues#issue/22, so if you have some ideas feel free to add them there, any help is appreciated :)
2. I think I got this one: if you've named your files 1.html, 2.html, 3.html... 16.html, then the correct alphabetical order is 1.html, 10.html, 11.html... 16.html, 7.html, 8.html and so on till 9.html. Since the framework orders files alphabetically that should explain why you have page 7 after 16 (and also 10 after 1 maybe?). Try to rename your file 01.html, 02.html, 03.html, etc..., rebuild your app and see what happen, I expect your problem to be solved.
3. I've been unable to reproduce the strange animation you mention while compiling and testing the framework untill I tried it on a device with the new iOS 4.2, then I saw what you are talking about. Thank you for point this to our attention, we'll be working for fixing that as soon as possible.

That's all, I hope this answer helps you as much as you have helped us.

**Comment by Xm4s** [comment] 2010-11-27 13:02
Since points 2. and 3. seems to be resolved and 1. is already discussed in another issue I'm closing this up.

Thanks again for pointing out the scrolling down bug in iOS 4.2 so we could fix it up for its release.

**Closed as completed** 2010-11-27 21:02 UTC
Labels: Bug

**Comment by javifr** [comment] 2010-11-29 20:37
Hi!
Baker fan here also!

What about this one:
"I've just one request that will make this framework complete. Think it's mentioned already. But something for pagenavigation (like TIME Magazine and others using the WoodWing framework or other frameworks) will make this a superwonderful project."

I would love love love this feature also!
