### ISSUE TITLE
iPad-Retine. Problem with the resolution.

### ISSUE THREAD

**Issue by Issean** [Simbul/baker#492] opened 2012-09-20 13:38 UTC
Hello,

we're creating an interactive magazine for iPad with Baker framework. It should support both iPad 2 and iPad 3 (Retina). We have the print edition of magazine, that we should "convert" into the digital version. The external graphic designer had made some layouts (.png-files) for Retina-display with the resolution 2048x1536.
My idea was to build the sites in html for the Retina-resolution (2048x1536) and scale them down for the other devices, such as iPad2 or iPad1 (1024x768). But I didn't find out how I can make it. It doesn't even work in Xcode simulator for iPad Retina (all fonts, pictures are huge and I cannot resize them).

Need some help.

Thanks in advance!

**Comment by folletto** [comment] 2012-09-20 14:12
You can do that using one of the standard HTML techniques around, for example:
- http://www.studiopress.com/design/css-background-size-graphics.htm
- http://css3.bradshawenterprises.com/blog/retina-image-replacement-for-new-ipad/

**Comment by ghost** [comment] 2012-09-23 21:28
This isn't necessary for EVERY image, but watch out when letting the iPad 1 and 2 downscale those huge 2048x1536 images. The iPad 2 usually handles those alright, but the iPad 1 really struggles when having to downscale all those images. What I always do is create two separate sets of images, one containing the regular sized images and the other the retina images. You can use the two methods mentioned for the implementation of those retina images.

The downside is that you'll have en extra set of images in your "book", but the app will work way better than letting those poor iPad 1's downscale 2048x1536 images :)

**Comment by Issean** [comment] 2012-09-24 09:10
folletto, rickmerkelbach,

thx for your help! I will try it today..

**Comment by Issean** [comment] 2012-09-25 08:08
I know why I cannot downscale. My "meta viewport" does not act right.  and I have no idea why.
Like I said, I build the sites for Retina-resolution. 
In html:  
`meta name="viewport" content="width=1536; initial-scale=1.0; maximum-scale=1.0; user-scalable=no;"`

thx..

**Comment by folletto** [comment] 2012-09-25 14:37
I don't think approaching the problem with a meta viewport helps, and even so, the width you specified is huge. Why did you put 1536px?

Just try removing it and working on the CSS / `media-query` parts, and just after that try with something like:

`<meta name="viewport" content="width=768; initial-scale=1.0;"/>`

**Comment by folletto** [comment] 2012-11-22 18:53
Hello! Did you solve it? :)

**Comment by folletto** [comment] 2013-01-19 22:59
I'm closing this due to the lack of follow-ups. Reopen at need.

**Closed as completed by folletto** 2013-01-19 22:59 UTC

**Comment by fcontreras** [comment] 2013-02-28 00:11
Greetings.. 

I dont think Baker is listening to the viewport meta tag.
I was creating a html page that reders correctly on safari but on the Baker view it remains the orginal size

The width is actually 960px and on portrait you need to scroll left/right to see the page, which doesnt happen on safari (same page) cause of the <meta name="viewport" content="width=960, user-scalable=no;" >

Im I doing something wrong.? was this meant to work like this?

**Comment by folletto** [comment] 2013-02-28 00:29
Please, open a separate issue for support, don't use a closed one on a different subject. :)

Still, quick answer before you open your own issue: I'm not sure the cause (even if it might be something that we inject from Baker to make sure the page is rendered 1:1), however Baker is made to support native resolution and adapt to that using CSS _media queries_, so I'd advise to modify the CSS to make the page work without meta viewport.

**Comment by fcontreras** [comment] 2013-02-28 15:09
Thank u for you quick answer. I fixed the layout by modifying the css code and removing the viewport.
