### ISSUE TITLE
Newsstand basic support?

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#217] opened 2011-11-20 16:08 UTC
Someone has created a free subscription to the Newstand? How? Baker needs to be implemented in xcode?

http://developer.apple.com/search/index.php?q=newsstand
http://developer.apple.com/library/ios/#documentation/StoreKit/Reference/NewsstandKit_Framework/_index.html
http://developer.apple.com/library/ios/#technotes/tn2280/_index.html

**Comment by folletto** [comment] 2011-11-25 17:54
This is a duplicate of the request on Issue #100, I'll close this one. :)

**Closed as completed by folletto** 2011-11-25 17:54 UTC
Labels: Discussion
