### ISSUE TITLE
Date format issue [was: Shelf connecting problems]

### ISSUE THREAD

**Issue by yujulio** [Simbul/baker#630] opened 2013-01-12 16:23 UTC
Hi, I'm having a weird problems with the shelf, I recently launched a Magazine for the iPhone only and I'm having reports from some people who can't download the issue from the Shelf, the only thing they see is "Connecting...", this happen to me before I launched the app but it solves itself, I even check the debug console and there's no issues.

Do baker have any timeout when it can't connect and download the magazine?

**Comment by nin9creative** [comment] 2013-01-12 16:48
What are you using to host your issues?

**Comment by yujulio** [comment] 2013-01-12 17:22
A hosting by a Venezuelan Provider. Is a shared hosting, we're just testing
and do not expect the needs of a VPS right now.

2013/1/12 Andrew notifications@github.com

> What are you using to host your issues?
> 
> Sent from my iPhone
>

**Comment by yujulio** [comment] 2013-01-14 20:07
I've been checking my hosting's connection log and there is a connection to the hpub file in some IP but the file size of their download is 0 byte, is like they never ever download anything. Any idea of what this might be?

**Comment by yujulio** [comment] 2013-02-06 20:33
Just launched another magazine for iPad and the issue is still there, have anyone have had the same experience? 

I'm thinking to move my hosting to a VPS, still I'm not sure if it is going to fix it. Any recomendation?

**Comment by nin9creative** [comment] 2013-02-06 22:49
I would try moving where you have the files hosted...

Warm Regards,
Andrew

**Comment by yujulio** [comment] 2013-02-07 20:56
Just moved my files to a Dreamhost VPS, still not working...

2013/2/6 Andrew notifications@github.com

> I would try moving where you have the files hosted...
> 
> Warm Regards,
> Andrew
> 
> Sent from my iPhone
>

**Comment by yujulio** [comment] 2013-02-07 21:46
Is posible that I, using iOS 6.0 as deployment target is causing this problem? Because I saw that there's many deprecations if I build the app using 6.0 instead of 5.0?

**Comment by sempeck** [comment] 2013-02-15 17:07
I have the same issue...

**Comment by yujulio** [comment] 2013-02-18 14:34
So, I have tried differents hosting, tested the app with older and the newest update of Baker even tested it with MagRocket, tried changing the content in the json, still, I'm having some devices that are stuck in the Connecting status.

I ran out of ideas of how to make this work...

**Comment by yujulio** [comment] 2013-02-18 20:37
Finally found out what the problem was and why almost no one had the same issue as me.

The problem was with the user's iPhone, most of the iPhone here in Venezuela are configured to use the region code "Venezuela", I changed it to United States and every download works fine. 

I came across this because from the debug log I always saw a Exception, this was "EXCEPTION the date argument cannot be nil". After I changed the region code this Exception did not apear anymore. So I'm guessing the problem was if the device didn't understand the argument it will not start the download.

Is there anyway to fix that? Most of my users are from Venezuela and I'm not sure how to bypass that exception and I'm an ignorant when is about Objective C.

Many thanks beforehand.

**Comment by Simbul** [comment] 2013-02-18 20:53
That is puzzling but very interesting.
My uninformed guess, at the moment, is that Newsstand Kit (which handles downloads) is getting a wrong date from the `shelf.json` file (which is the only place where we have dates).

Since you say that the issue goes away by changing the region to US, this might have to do with locales and date parsing.

This is all guesses though. Do you know which line was causing the exception? Was there anything else that looked wrong in the log?

**Comment by yujulio** [comment] 2013-02-18 21:12
This was the log:

> 2013-02-18 13:44:07.978 Revista Nos3 Edicion iPhone[3118:907] ====== Newsstand is enabled ======
> 2013-02-18 13:44:08.471 Revista Nos3 Edicion iPhone[3118:907] Successfully added skip backup attribute to item /var/mobile/Applications/E2DB4377-8321-4D53-8634-24CE0923D10F/Library/Caches/shelf.json (iOS >= 5.1)
> 2013-02-18 13:44:08.492 Revista Nos3 Edicion iPhone[3118:907] EXCEPTION the date argument cannot be nil
> 2013-02-18 13:44:08.940 Revista Nos3 Edicion iPhone[3118:907] Successfully added skip backup attribute to item /var/mobile/Applications/E2DB4377-8321-4D53-8634-24CE0923D10F/Library/Caches/shelf.json (iOS >= 5.1)
> 2013-02-18 13:44:08.945 Revista Nos3 Edicion iPhone[3118:907] EXCEPTION the date argument cannot be nil
> 2013-02-18 13:44:08.947 Revista Nos3 Edicion iPhone[3118:907] Refreshing eglantinazingg view with status remote
> 2013-02-18 13:44:08.987 Revista Nos3 Edicion iPhone[3118:907] Refreshing eglantinazingg view with status remote
> 2013-02-18 13:44:10.601 Revista Nos3 Edicion iPhone[3118:907] Refreshing eglantinazingg view with status connecting

I commented "[dateFormat setDateFormat:@"yyyy-MM-dd HH:mm:ss "];" from IssueManager.m, tried the app in the iOS Simulator and the download never started, it got stuck too in connecting, so I'm guess the problem is with that format.

**Comment by Simbul** [comment] 2013-02-18 22:01
Ok, from the log it looks like the exception is being raised when parsing `shelf.json`, which is consistent with the hypotesis (by the by, I think you're not using the latest `master`, correct?).

Can you copy and paste here the dates in your `shelf.json` file?

**Comment by yujulio** [comment] 2013-02-19 13:06
Yes, I tested this with the first release of Baker 4.0 and the lastest.

> > "date": "2013-01-04 12:45:30"

I'm using this date.

**Comment by yujulio** [comment] 2013-02-20 15:55
Hi again, got some reports here.

After I change the International locale to US, the downloads started in all the devices I could test and I got this log:

> 2013-02-20 09:12:24.193 Revista Nos3 Edicion iPhone[559:907] added eglantinazingg 2013-01-04 17:15:30 +0000

If I change back to Venezuela, I still can download. Anyway, most of my potencial users have never changed their locale to US and most of them are clueless about how to do it and why they have to change it so they can download the magazine.

I've been reading Data Formating Guide from Apple's documentation to see is there's anyway to fix this by forcing the parse to be from a en_US locale but their doc are kinda confusing. Maybe this line could fix this:

> >  NSLocale *enUSPOSIXLocale = [[NSLocale alloc] initWithLocaleIdentifier:@"en_US_POSIX"];
> >  [dateFormat setLocale:enUSPOSIXLocale];

Just not sure where to put it.

**Comment by Simbul** [comment] 2013-02-20 22:47
It's a bit difficult to test this since I can't reproduce the issue on my iPad, regardless of the locale I set.

However, I've gone through the guide as well and I think you are on the right track with `en_US_POSIX`. I've tried a fix based on that in the [fix-date-parsing](https://github.com/Simbul/baker/tree/fix-date-parsing) branch. Give it a spin and let me know if it works for you.

**Comment by yujulio** [comment] 2013-02-21 19:37
Ok, thanks, as soon as I'm able to test it I'll give you the report, right now I ran out of devices that cannot download it, I'll look for someone who can lend one to me.

**Comment by yujulio** [comment] 2013-02-25 13:21
Seems to be working with this fix now,  thanks a lot to you guys. 

I notice that this fix move the status bar a little bit down than usual:
![Captura de pantalla de Simulador iOS 25 02 2013 08 49 25](https://f.cloud.github.com/assets/678854/191884/056d9f0a-7f4e-11e2-8815-ef193c0a5f1e.png)

**Comment by Simbul** [comment] 2013-02-26 00:13
It's extremely unlikely that the issue you see with the status bar is connected to this fix. Probably something else that got in `master` in the meantime.
Please open a separate issue if you think that's a bug.

I'm closing this one as I've merged the fix in with commit 86785e192ae4f625256fe82d969c73d6416bdeac. Thanks for your very detailed bug reports :)

**Closed as completed by Simbul** 2013-02-26 00:13 UTC
Labels: Bug, Investigation Required

**Comment by fcontreras** [comment] 2013-05-17 00:57
Having the same issue.. but unable to reproduce in any of my devices.. 
Thanks for the fix @Simbul ... yet I never saw the issue locally.
