### ISSUE TITLE
Anyone design with Indesign and output to images for a publication?

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#408] opened 2012-05-11 01:09 UTC
I'm trying to come up with a workflow for a prospective client who likes to do their print design with Indesign...  They like the Mag+ solution that outputs to Mag+ special file that is able to be designed in Indesign.

However they are irritated at the high price of the Adobe DPS solutions.  They want to do the design with their current workflow and leave placeholders for video and other interactive elements that are to be added later using HTML5.

I have no idea how to approach this...  Obviously I tried to push a full HTML5 development, but I can't make any traction with that.

Just curious if anyone else has done anything different.

This will be deployed on the Bakershelf framework.

Andrew

**Comment by andersonchagas** [comment] 2012-05-11 01:47
Maybe you can use .jpg pages exported from indesign in your .html files. Where are videos, just make a div positioned on right place..

the z-index of interactive elements is greater than the background (the page art exported from indesign).

I think this will work..

**Comment by nin9creative** [comment] 2012-05-11 02:36
That's what I was just looking at!  That probably would work :)

**Comment by CopperF0x** [comment] 2012-05-13 21:56
Can't the newer versions of InDesign output in HTML directly?  (I was under the assumption some portion of Baker mags were being created with it)

**Comment by jcampbell05** [comment] 2012-05-14 10:02
In the New InDesign CS5.5 it has "Improved support for ePub and HTML5 Exporting"

**Comment by nin9creative** [comment] 2012-05-14 14:30
I tried doing a few different exports to HTML, but it didn't look the same.  I don't know if there are other settings
or something - but the output didn't look close to the actual design.

Andrew

**Comment by jcampbell05** [comment] 2012-05-14 18:31
How does it look different? show us images. 

The problem is inDesign is trying to use new HTML5 technologies where older apps would of just turned it into images which goes against the nature of HTML Design where text and the layout should adapt to the screen size. The con is obviously your layout won't be pixel perfect but to be honest this is a trade off you should be prepared to face in general if you are using HTML based technologies especially if you want a satisfactory experience for the user.

Try exporting it in ePub though if you arnt sure see how that looks (use a epub reader) if it works then look inside the epub and there should be a load of html files containing your pages of your magazine

If that doesn't work then the options are really:
- Use images but with positioned divs for the dynamic content, bad experience for the user but lots of control for client
- Except that HTML isn't a fixed page and your design might not look the same even if inDesign can't export it very well
- Recode it yourself in HTML 
-  Stick to Mag+

**Comment by pterotype** [comment] 2012-05-16 18:05
We're doing that with our magazine. We fab it up in InDesign, output a PDF, then convert all pages to pngs. Then import them into the Baker Framework which gives us full html5 options to code on top of those pages: videos, CSS widgets, etc. Therefore, we just use InDesign to design, and the Baker Framework for coding interactivity. No Adobe DPS required!

**Comment by CopperF0x** [comment] 2012-05-16 18:21
pterotype & others - thanks for the feedback!   Ive been looking into other e-mag providers as a short-term solution until Newsstand support is fully available in Baker.  Given the rest of the industry is predominantly InDesign-driven, it's nice to know there are strategies for porting InDesign development back over to Baker.

**Comment by nin9creative** [comment] 2012-05-23 18:02
If someone came up with a quick set of utils and a framework for doing this sort of thing it would be a pretty interesting alternative to using Adobe DPS or Mag+ etc....  Basically the pattern of using InDesign, exporting images and the HTML / Javascript for adding certain overlay elements for interactivity.

I know quite a few people that would probably like to ditch the expensive proprietary stuff.

**Comment by nin9creative** [comment] 2012-05-23 18:03
@pterotype Do you have any publications on the app store that were designed this way?

**Comment by pterotype** [comment] 2012-05-23 18:05
Hi there,

## Just about to release our app, The Uninvited, as a newsstand app rather than a standard app. Possibly by end of week or next week.

Adam D. Blainey
Rock Bay Media
Interactive Publishing &
Online Broadcasting

**Comment by pterotype** [comment] 2012-05-23 18:20
In my opinion, Baker already does this. It's not a perfect framework, as there are still some things not implemented, but it's not bad.

## Again, it is quite easy to design a magazine in InDesign and output each page as an image. There are probably different ways to skin that cat, but I just export as PDF, then create images for each page. The Baker framework then gives me HTML for each page, onto which I can code up elements in CSS or embed videos, or whatever. So, really, my approach to it is to do all the interactive programming in HTML on top of PNG files within XCode. I DO NOT do anything interactive in InDesign, I find HTML is much easier and robust. Interactivity in InDesign is just not my thing.

Adam D. Blainey
Rock Bay Media
Interactive Publishing &
Online Broadcasting

**Comment by mutador** [comment] 2012-05-23 20:25
we carefully....in newipad the .png or j.pg don´t see well in 72ppi. needs jpg 150ppi( more heavy book), 
in our new magazine
i put all the text like html and only put jpg for images whit some sharpen( see great in newipad)....
the text in html looks fantastic in newipad but the text like jpg or png( best editables pngs) don´t looks well

i desing the pages in fireworks and make the templates in html....
you can use embed fonts in css

coming son ..paperlove magazine

**Comment by pterotype** [comment] 2012-05-28 16:42
Look forward to Paperlove, mutador.

**Comment by CopperF0x** [comment] 2012-07-31 03:37
I felt this was relevant enough to share.  I feel it would be a boon to Baker developers to have such a tool.   Hope to see it comes to fruition.

http://www.kickstarter.com/projects/ajarproductions/indesign-to-html5

**Comment by folletto** [comment] 2012-08-20 21:39
The project above has been successfully funded 4 days ago. So, let's wait for it to be developed so we can have a great tool to add to Baker's production chain. :)

**Comment by mutador** [comment] 2012-08-21 08:33
adobe mus works perfect for one landscape or portrait mode, i thinks is better than indesing.

**Comment by charlesdelacroix** [comment] 2012-10-24 19:36
Hello everyone, 

I just began to work with Bakers Framework and it seems I´m having some problems to create the Package. I have some questions for you professionals to see if you can help me.

-Is there any specific editor to write the JSON file? Is this .html, .txt or any rare extension?
-Once the package is created and runned by the Baker.xcodeproj i get a black screen in the simulator. Did anyone got this problem too?
-All the pages must be HTML or CSS?

Thanks for your help...

**Comment by folletto** [comment] 2012-10-25 12:51
These are a lot of questions! :)

I would advise you to start from the template you can download from the website and work start experimenting from there. You'll see how the json file works (no you don't need a specific editor), how to package it and how the pages are built. :)

**Comment by Simbul** [comment] 2013-04-08 22:43
The Indesign plugin has been released and it's being discussed in #756, so I'm going to close this thread.

**Closed as completed by Simbul** 2013-04-08 22:43 UTC
Labels: Discussion

**Comment by biapar** [comment] 2013-04-13 12:30
@pterotype: How to convert PDF to PNG? How to build HTML5 from PDF? Do you write HTML file for each PNG page ( <img src="" .... /> )?
