### ISSUE TITLE
Three-cards: smoother transition between two pages

### ISSUE THREAD

**Issue by botic** [Simbul/baker#27] opened 2010-11-27 18:15 UTC
Was: Smoother transition between two pages

At the moment there is a short flash between two page loads, specially when they have more images. Sometimes I see the old page for a short time after the number fades out and before the switch to the new one. Maybe there is a way to pre-render the next and previous page to make it more smooth and faster. Or is this already in? (Sorry, I have no experience with Obj-C coding / iOS SDK)

**Comment by folletto** [comment] 2010-11-27 19:04
Unfortunately that's a technical limitation that we're trying to solve since day one. We're working hard on that, but so far no solution.

Thanks for the pointer however, because it's important to know that nags people. :/

**Comment by botic** [comment] 2010-11-27 19:24
If I could I would help you with that. I will ask some iOS guys the next days if they know a way to improve that. Btw. great what you have done so far, I'm waiting for the rotation pull request to be merged.

**Comment by MacBoy** [comment] 2011-01-10 15:07
Yes -- I agree with this bug report!
1.  Swipe to see the next page
2.  Flash of white appears with page number and spinner
3.  For a moment, the old page is then shown
4.  Then the new page is displayed 

I thought with UIScrollView that one could pre-load page content "offscreen" ?

I also thought I saw code to do this within the Baker app.

Yet, I am new to iOS development, I leave it to the experts.  I only know enough to ask questions and make possible suggestions.

Thank you for such a nice framework, a few more features and fixes will make it such a valuable tool !!!

**Comment by folletto** [comment] 2011-01-10 15:12
We spent days on this, unfortunately we don't have a solution yet. :|

~

To answer your question, the previous version of Baker used a three-panes approach, but we left it behind because it wasn't feasible with the current iPad hardware (not enough memory) if you started building pages more complex than a few scrolls of text).

We are still trying to solve this, thanks for the feedback and... well if it happens, help us asking around on how to fix this. ;)

**Comment by MacBoy** [comment] 2011-01-10 15:32
That is interesting that memory is a constraint.

I embedded Magaka into Baker, it was able to swipe through the pages with no delay.  Within the book folder, I changed Magaka's index.html to Chapter 01.html.  Then it simply ran fine.

Please note that Magaka handled the page transitions and page displays.  Baker only knew about a single page, the Chapter 01 page.  All other pages were handled by the Magaka JavaScript framework.

So perhaps it is possible to buffer the next and previous pages.

I too will ask a few iOS developers if they know the solution.

**Comment by folletto** [comment] 2011-01-10 15:34
Yep, javascript works fine. :)

If you find a way to buffer them, we'll add the change as soon as we can. :)

**Comment by fourthversion** [comment] 2011-01-15 05:04
I wrote a solution for it for a friend. The trick was  in webViewDidFinishLoad:. I'm assuming that UIWebView calls out to the delegate in the same thread it is finishing the load call. So while your delegate receives the message that the web view is finished loading, you see a delay. So when the call unhide the web view is performed it causes a "jitter" if you will and you see the old page before the new page.  The way I solved it was by creating a function (-(void) revealWebView:(UIWebView*) webView and replaced the direct webView reveal call with this one via performSelector:withObject:afterDelay:. This allowed the webview to actually finish loading (in my opinion) and the reveal to occur after the page is loaded.  The code is below. FWIW.
- (void)webViewDidFinishLoad:(UIWebView *)webView {
  // Sent after a web view finishes loading content.
  
  // If is the first time i load something in the currPage web view...
  if (webView == currPage && currentPageFirstLoading) {
      NSLog(@"(1) currPage finished first loading");
  
  ```
  // ...check if there is a saved starting scroll index and set it
  NSString *currPageScrollIndex = [[NSUserDefaults standardUserDefaults] objectForKey:@"lastScrollIndex"];
  if (currPageScrollIndex != nil) [self goDownInPage:currPageScrollIndex animating:NO];
  
  [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(onTouch:) name:@"onTouch" object:nil];
  
  //[self loadSlot:+1 withPage:currentPageNumber + 1];
  //[self loadSlot:-1 withPage:currentPageNumber - 1];
  
  currentPageFirstLoading = NO;
  ```
  
  }
  
  // /!\ hack to make it load at the right time and not too early
  // source: http://stackoverflow.com/questions/1422146/webviewdidfinishload-firing-too-soon
  //NSString *javaScript = @"<script type=\"text/javascript\">function myFunction(){return 1+1;}</script>";
  //[webView stringByEvaluatingJavaScriptFromString:javaScript];
  
  [self spinnerForPage:currentPageNumber isAnimating:NO]; // spinner YES
  //[self webView:webView hidden:NO animating:YES];
  [self performSelector:@selector(revealWebView:) withObject:webView afterDelay:.1];
  }

-(void) revealWebView:(UIWebView*)webView {
    [self webView:webView hidden:NO animating:YES];
}

**Comment by MacBoy** [comment] 2011-01-15 05:17
Wow -- that is awesome you were able to make the old page flash go away within Baker!

Could you send me your file?  That way, I won't have to rely upon my poor coding skills.  (it looks funny due to the text formatting in the comment area, I fear something may have been deleted)

I have sent you a private message with my personal email address.  I'll test it out!

Thanks!

**Comment by folletto** [comment] 2011-01-15 17:09
@fourthversion
Would you like to make a patch or merge request so we can credit you in the code? :)

**Comment by botic** [comment] 2011-01-16 20:08
Would be great to have this in 1.1!

**Comment by fourthversion** [comment] 2011-01-16 20:17
@folletto :) I don't mind not getting the credit. Ultimately my solution was just a quickie solution. I think the ultimate solution should do something more than just reveal the web view, possibly handling the passing of the parms for hidden and animating. If you really want me to I can do it the way 'I' think it should be written. But if you (I'm assuming this is your framework) want to take a stab at the true solution then go for it. Just let me know, I can go either way.

**Comment by esquareda** [comment] 2011-01-16 23:12
Big thanks for @fourthversion - my Baker book is pretty smooth now. Though, he is right - we had some long discussions about this and it appears the loading (or pageDelayer?) is not working quite right. I'd love to see fourthversion jump in!

Here is a quick little video of the book so far (some of the transitions were too fast for Jing to record, I assure you it's smooth) http://screencast.com/t/BWHkgimGhIBd

**Comment by folletto** [comment] 2011-01-16 23:12
If you think a better solution exists, then definitely go for it. We are quite stuck now because it seems something related with the internals of UIWebView, and so it's probably some kind of hack over it. :)

My "ownership" on the framework is just about trying to create something that's satisfying as the "ideal" book solution, but to go there me and the other developers surely need a lot of help. :)

I think we'll still test and try to include the quick solution in the 1.1 as an interim solution. ;)

**Comment by folletto** [comment] 2011-01-19 01:35
We added the solution to the current master, it's going to be in the 1.1. I won't close this bug since I'd gladly avoid the 0.1 delay it generates, but I think it's better this way for now. :)

**Comment by esquareda** [comment] 2011-01-19 19:45
Great! Ideally, the next and previous pages would pre-load. Then we wouldn't need a delay or loading animation at all. It even looks as if there is code present to attempt that functionality but appears to be commented out.

Of course, this premise is all based on my discussion with @fourthversion - I don't know jacksquat about Xcode or Objective-C. ;-)

**Comment by folletto** [comment] 2011-01-19 23:08
As I've said above, the original Baker used three panes with pre-loaded content. It was already ready, already built. It was our first approach, if you check the codebase before the release date. But... it hit a few walls:
1. The bug we are discussing here was still present
2. While pre-loading, the interface was basically locked
3. With bigger pages there wasn't enough memory, so it still flashed white and loaded

We have changed a bit the code in these months and we are surely a bit more expert, so we might try again re-implementing it and see if we are able to workaround those issues, but these are the reasons why we reverted back to a single page view: the experience was awful.

**Comment by frantovar** [comment] 2011-01-24 17:15
Hi guys,

I have the same problem but I can not understand if there is any solution. Is the proposal made by fourthversion?

Thank you very much

**Comment by folletto** [comment] 2011-01-24 18:20
It's already included in Baker 1.1, released a few days ago. ;)
The bug is not closed because I'd try to find a better solution.

**Comment by frantovar** [comment] 2011-01-24 19:55
Hi folleto, thanks for your response.

So the problem is solved since you released version 1.1?

Last week I upgraded to 1.1 but, today testing the iPad, I've noticed this problem.

There is a workaround until you find a final solution?

A greeting and thanks for your great work ;)

**Comment by folletto** [comment] 2011-01-24 20:45
The workaround is the one already released, sorry. :|

**Comment by frantovar** [comment] 2011-01-25 10:32
Do not worry, you have done a great job. And will improve with time;)

**Comment by mimetic** [comment] 2011-05-14 18:47
Over at NimbleKit, the author says that one simply cannot make smooth page transitions from page to page, when each page is another HTML browser. That's how it's done in Baker, I understand, and that's how it is done with NimbleKit.

There is a solution, however. When you want a smooth transition, say between photos, you keep all the data on one HTML page and use JavaScript to change pages. I'm doing that with jQuery, and so far, it works fine.

**Comment by Xm4s** [comment] 2011-05-23 23:13
To address the problem of the smoother transition we have re-implemented the "three-cards" views approach.

Basically now, a part from loading the current page, also the next and the previous page gets loaded outside the screen.
With this solution the transition between two subsequent page doesn't present any loading delay or flash of content. 

However, since loading and rendering a html page in a UIWebView is a slow operation (and also seems impossible to speed it up), sliding too quickly between pages will make the old page numbers and loading wheel reappearing.

The "three-cards" approach is released under the "three-cards" branch of the repository.
We would like to hear some feedback about it, so please try it out and let us know how you found it.

Thank you :)

**Comment by mimetic** [comment] 2011-05-24 02:59
I have updated with the "three-card" and there is an immediate problem. When I slide to a new page, if the new page has not loaded, there is only a white page to slide onto the screen. Or, if the page was loaded but has been cleared from memory somehow, the page that is to be slid onto the screen is white.

When it works, it is great. However, it isn't reliable, and the white pages look bad, since I have black pages.

Perhaps you could always preload the black page --- quickly --- then try to load the big, real page?

**Comment by folletto** [comment] 2011-05-24 08:59
That's basically the reason why we removed it past november. It usually works when the pages aren't huge, but as you can see the problem appears quite quickly.

What do you mean by preloading the black page? :)

**Comment by therabidbanana** [comment] 2011-05-25 17:45
@mimetic: is this with the SCROLLVIEW_BGCOLOR set to black? That might help if you haven't set it yet.

One issue I'm seeing with the three-card branch in my testing - orientation changes that were already sort of slow have become unbearably slow, since now I have to wait for three separate pages to reflow to the orientation. Maybe it'd be possible to free up the previous and next cards before orientation change, then start reloading them after the orientation change has occurred? I suppose I also need to make some changes to my book to help speed up those orientation changes.

**Comment by folletto** [comment] 2011-05-25 17:48
That could be an interesting idea to test, I'm not sure however if it's slower to do the reflow, or reload the pages.

**Comment by therabidbanana** [comment] 2011-05-25 17:51
Well, my problem is that the orientation change doesn't actually show on screen until all of those pages are _ready_ to rotate. So I'm waiting as much as 5 seconds for a rotation of the device to actually translate to a rotation of content. If those extra webviews were destroyed before rotation, the rotation could occur quicker - then, when it's less noticeable, slow down the device to load those extra pages.

**Comment by folletto** [comment] 2011-05-25 17:52
Ok, I got it. Yes, I guess that's a good way then. :)

**Comment by mimetic** [comment] 2011-05-25 21:10
Perhaps we're barking up the wrong tree. I have slow load times because I have many photographs on the page. Shouldn't we look at having the page load quickly, meaning we don't load large images immediately, but allow them to load after the page loads? I am assuming the page is not considered loaded by the browser until all graphics are also loaded, and I could be wrong.

I figure that rendering of a page without graphics should be quick, even if it is long.

**Comment by therabidbanana** [comment] 2011-05-25 21:16
Another thing I'm noticing in my testing is that if a page has started fading in right as you swipe to the next page, it can get a little choppy trying to animate the swipe and the fade in at once.

**Comment by Xm4s** [comment] 2011-05-25 21:39
Thank for the feedback guys :D

I'm currently doing some experiment to improved Baker overall performance with the three-cards navigation.
As soon as I get some results I'll let you know, in the meantime keep up posting your feedback and ideas, you're doing a great work :)

**Comment by therabidbanana** [comment] 2011-05-25 21:47
Another thing that might help performance (haven't played with it) - is to not start loading slots -1 and +1 until slot 0 has fully loaded. I'm noticing when I jump to a page from a link, page loads are slower than they are without the three-card setup and the log is showing all three pages starting to be requested at the same time, which is probably contributing to that.

**Comment by therabidbanana** [comment] 2011-05-25 21:52
Thanks for your work as well @Xm4s! When used as intended (slowly paging through) the three card approach is looking great for our book. I'm just doing as much as I can to break it so we can work out the rough patches :D

**Comment by jameskatt** [comment] 2011-06-01 06:31
I would examine Chris Mayer's code to see how he accomplishes smooth transitions between HTML pages. http://www.chrismayerapps.co.uk/buycode/index.html

**Comment by folletto** [comment] 2011-06-01 11:58
Which one you are referring to? It seems that only "Advanced Book App" does that, and it's still very basic content with basic animations and features. I might have missed the one you were referring to, tho. :)

**Comment by mimetic** [comment] 2011-06-02 17:01
FYI, I'm accomplishing the smooth page transitions inside the HTML page, using Javascript. I've also had to do some memory management, essentially "unloading" large images when not needed, to avoid memory errors. Perhaps the final solution is a mixture of both? 

For example, I suspect my HTML pages should probably load the main info via Javascript, AFTER the initial page load. That way, the transition will be quick, even if the page is loading in the background.

**Comment by folletto** [comment] 2011-06-02 21:17
Yup, it's absolutely possible in pure HTML/JS. The idea is that if you prefer a pure JavaScript solution you can still use Baker for it, and adapt it your way.

We have an ongoing discussion about it, however for now we think that the current Baker + Laker approach is still the good one, we don't wont to force any specific HTML to book creators, like nobody would try to force any CSS or JavaScript framework for the web.
What I could suggest is to create your "packaged" solution, we'll list it in the public Baker website like we are doing with Laker, in order to have a more rich ecosystem.

And in the future, we'll see... maybe we'll start incorporating some JavaScript as well. :)

**Comment by mimetic** [comment] 2011-06-02 21:31
Frankly, I'd prefer NOT to use the Javascript! I was simply forced to, since I don't program C! I mentioned it merely to suggest that the final solution might require both. I assume one cause of the white page-flash is the delay in loading large browser pages. Also, that loading a large page takes a lot of memory. So, a JS which shifted the loading might solve the white flash problem?

**Comment by folletto** [comment] 2011-06-02 22:05
I prefer that too. ;)

What do you mean by shifted? :)

**Comment by mimetic** [comment] 2011-06-02 23:38
By "shifted" I mean, instead of the browser loading the entire page when the C programming opens the page, let Javascript do loading after the page is "loaded." So the actual loading of the page information is done by the Javascript. An elegant solution, but it might help.

**Comment by folletto** [comment] 2011-06-03 10:22
I can't think of a clean enough way to do that, would you like to try to implement it in a way that doesn't change the page building process for authors? :)

**Comment by mimetic** [comment] 2011-06-03 20:31
Such a solution would require either a Javascript loader (which I've seen somewhere), which loads external files, OR to put the page itself initially inside a DIV to render after loading. Would it be acceptable to provide an HTML template that users would have to comply with, e.g. putting their HTML in a particular part of the code?

**Comment by mimetic** [comment] 2011-06-03 22:40
(Since this issue was bounced over here, I'll have to address it here, right?)

The following code DOES delay the page loading. And, if I set the delay (afterDelay, at bottom) to 0.0, my pages loader faster. 1/2 second faster, actually. I don't see any stutter when pages change, so I'm not sure why this is necessary. 
- (void)gotoPageDelayer {
  // This delay is required in order to avoid stuttering when the animation runs.
  // The animation lasts 0.5 seconds: so we start loading after that.
  
  if (currentPageIsDelayingLoading)
      [NSObject cancelPreviousPerformRequestsWithTarget:self selector:@selector(gotoPage) object:nil];
  
  currentPageIsDelayingLoading = YES;
  [self performSelector:@selector(gotoPage) withObject:nil afterDelay:0.5];
  }

**Comment by mimetic** [comment] 2011-06-03 22:44
Another idea:

Following upon this (http://stackoverflow.com/questions/1422146/webviewdidfinishload-firing-too-soon), if we can send javascript to the page AFTER it loads, then we can command it to complete rendering. I'll see if I can mock this up.

**Comment by mimetic** [comment] 2011-06-03 22:47
And (sorry for the spray of ideas): Can you cache smaller pages with the three-page solution while forcing large pages to load (even if slowly)? This would mean small pages are smooth scrolls between them. This would be good, because then I could have single, simple HTML pages for, e.g. the forward contents, introduction, and that would feel natural. Then, between larger chapters, there might be a delay, but that's OK.

**Comment by folletto** [comment] 2011-06-03 23:39
Quickly:
1. We don't want to impose templates. If someone wants to build a template to make everything faster, we will be glad to support it in addition to Baker, but Baker should allow _complete_ freedom in managin the HTML. That's why I was suggesting to developer it and see any possible integration with Laker. Consider also that iPads are going to be faster year after year. ;)
2. You have removed it on trunk or on the three-cards branch? And did you try _every_ action possible? Because it was introduced to avoid bad issues in some loads, but in the three-cards branch it might not be needed anymore.
3. That will depend on a template, however... and the template will already know when the HTML has completed loading. ;)
4. Well we are already doing all the caching possible - that's basically what the three-cards is. :)

**Comment by mimetic** [comment] 2011-06-04 02:06
In response:

# I

1) Gotcha. No templates, no JS requirements
2) I remove it on trunk and three-cards. I have had some weird bad loads with three-card but I cannot reproduce them reliably. Seemly random, dammit.
3) No templates, got it. 
4) OK.

# II.

After finding out I could change the background color in the C code (I don't program C, by the way)....

OK, I've just installed the three-page again, with one massive modification: I've changed the SCROLLVIEW_BGCOLOR to black because my HTML pages are black.

#define SCROLLVIEW_BGCOLOR blackColor
#define PAGE_NUMBERS_COLOR whiteColor

Here's what I see:
1) Looks great
2) Occasionally, if I swipe from page 1 to 2, I get a flicker from page 3 for a quick moment. My page 3 (in this scenario) has a bright colored background, so the flicker is noticable, while it is NOT noticable in other cases (because of black backgrounds).

I suspect that flicker is something like a page bounce effect of some sort. It seems the new page arrives in place, shows a fraction of the next page, then restores itself in place. A very slow swipe does not create this effect!!!

If this were resolved (and it is not terrible, just annoying), the three-card solution seems to work great. 

Except with the iPad simulator, I get occasional and unpredictable wrong page loads. I can't figure that one out. E.g. I got backward and it has loaded the wrong pages. Might be combined with links in my pages. Sorry I can't be more detailed.

# III.

Added something interesting. Since you took out the double-tap navigator bar in three-page, I've done this. My change is at line 775. I've made a single-tap call a page javascript function, allowing me to show my own nav bar. Better than a "click" event call, which does weird flashes and stuff.
         [self changePage:page];

```
} else if (touch.tapCount == 1) {
    //NSString *javaScript = @"BakerSingleTap();";
    [currPage stringByEvaluatingJavaScriptFromString:@"showNavigator();"];
    NSLog(@"Hey! do my JS!: showNavigator();");

} else if (touch.tapCount == 2) {
    [self performSelector:@selector(toggleStatusBar) withObject:nil];
}
```

**Comment by mimetic** [comment] 2011-06-04 02:10
And, whatever changes you made with the tapping and scrolling also disabled my javascript scrolling. DAMN!

**Comment by folletto** [comment] 2011-06-06 21:07
Ok!
1. We are checking the delay
2. We are checking the random bug you found
3. The flash of content: it existed since 1.0, unfortunately it seems related to a UIWebView bug under certain circumstances. We hope it's going to be fixed under iOS 5.
4. We are already switching to black. It seemed a huge request. :)
5. The navigator wasn't there because it was a different branch, now everything has been merged to master, both three cards and navigator. :)
6. What did it disable? Did you try the last master? :)

**Comment by Xm4s** [comment] 2011-06-06 21:36
Hi Mimetic!

The 0.5 sec delay before loading the page was introduced to avoid multiple loading requests on the uiwebview when a user quickly tap on the left or right side to turn multiple pages at once. Removing it could cause the page turning to slow down and stutter a bit (because every time a page is turned the uiwebview try to load a page), but it's worth looking into it.

By the way we merge the three-cards branch into master, we'll continue work on this issue there :)

**Comment by Xm4s** [comment] 2011-06-12 16:24
As @therabidbanana suggested I've just adjusted three cards method to load first slot 0 (current page) then slot +1 (next page) and finally slot -1 (previous page). This should improve perfomances a bit as well as reduce the chance of memory problems.

Tests and feedbacks are welcome as usual, thank you :)

**Comment by therabidbanana** [comment] 2011-06-12 18:11
I had a random thought the other day - would it be possible to save screenshots of each rendered page and show those while  the actual webview is loading behind it? I don't know if that'd give any sort of performance hit, but it might give the appearance that the pages are loading faster than they really are.

**Comment by folletto** [comment] 2011-06-12 18:19
Well, that's something tha @Xm4s proposed too.

We never tried, so I might be wrong, but there are a few things to consider:
1. When? We can't ask the users to build an image for every page, and it might be a huge performance it on caching.
2. The interaction: if the user will se the image he will expect to interact with it too: so he swipes, starts scrolling and... nothing happens.

**Comment by therabidbanana** [comment] 2011-06-12 18:39
Yeah, it's definitely something that'd have to happen on the fly - and saving those images would possibly cause a performance hit (though maybe, if you wanted as a developer, we could make it so you can pull those images back off the device/simulator and save them inside the book). 

I would guess that to have the full benefit, we'd need to save full-height screenshots so that they could be scrolled (though obviously you'd not be able to click links or interact with javascript elements). I think you could still show a loading icon over a slightly blurred/grayed out screenshot - since I think the main benefit is being able to see what the page will be before it finishes loading - especially when you're flipping through pages to try to find a specific one, rather than instant interactivity (though both would obviously be better :D).

**Comment by folletto** [comment] 2011-06-12 19:05
From an experience point of view I'm dubious on the reception of a normal user of such a loading, I'm worried that it might have a low cost/benefit ratio, considering that iOS will get more and more optimized and hardware is going to be better and better.

But as said, it might be worth a try.

I'm also thinking of trying a JS/HTML approach as suggested my Mimetic and others, in order to keep the HPub format as-is, while maybe getting better result on swipes.

**Comment by therabidbanana** [comment] 2011-06-12 19:12
Maybe I'll play around with it a bit after I've got basic multiple hpub support working. You're right, seems like it'll probably have a pretty low cost-benefit ratio. 

I was just playing with some of the big publisher magazines like Wired and saw how fast they can load pages and was trying to figure out if there was a way we could pull that level of interactivity off - my guess was they probably just have flat images of pages, which are much cheaper memory-wise to render. As it stands, that's probably the last thing to worry about though.

**Comment by folletto** [comment] 2011-06-12 19:25
Yes, they do. It's a kind of a mixture of high-res images and XML to describe the interaction that you can have there. Think of it as images with overlaid a map of touchable parts. They can optimize a lot out of it due to the small number of possible things you can do there.

**Comment by laswell** [comment] 2011-06-14 00:48
OMG, when did the "index nav bar popup" feature very very cool! thank you all for your hard work, 
cheers

**Comment by folletto** [comment] 2011-06-14 01:06
It was the Feature #17 closed at the end of last month, borrowed and enhanced from Laker. ;)

**Comment by laswell** [comment] 2011-06-14 01:19
You Fabulous Baker/Laker boys, How did I miss that one, thanks you so much, great feature!

**Comment by mimetic** [comment] 2011-06-14 06:52
FYI, I have a working JavaScript swipe going, extending from Laker. The JS builds the swipable area using templates, etc., it load/unloads images, etc., to reduce memory use, although I still have trouble with multiple page loads taking memory. Or something.

However, it seems unstable. At times, images won't load. Rotating and tapping enough can confuse it.

I'll package up a reduced size version of the latest iteration so you all can play with it.

**Comment by folletto** [comment] 2011-06-14 10:43
That's great! :)
Let's see, maybe we can optimize it to work better than the native solution. ;)

**Comment by mimetic** [comment] 2011-06-14 20:56
Here it is: http://dl.dropbox.com/u/13346155/book.zip

I made it only two chapters, for testing, and the images are more compressed.

**Comment by laswell** [comment] 2011-06-14 21:27
Thats very cool mimetic, i wish i kew more to help but for now i'll have to be satisfied being a tester for you clever guys! vcool work!

**Comment by mimetic** [comment] 2011-06-14 21:37
The flash I'm seeing with "three cards" is from a bounce effect. When I swipe quickly, the screen scrolls to the next page (good) but then continues to the next-next page for a second, and then bounces back. Can you tune the deceleration to avoid that? That would solve a lot!

**Comment by mimetic** [comment] 2011-06-14 22:02
OK, I've been perusing everyone's scrolling pages, and everyone (including Apple samples) have this issue. However, they also seem to have the next-next page loaded...or they match backgrounds. In other words, the bouncing is probably here to stay. Let's look consider at loading not 3 pages, but 5.

**Comment by Xm4s** [comment] 2011-06-15 20:54
@mimetic
I've downloaded your book example but I wasn't able to test the javascript swipe nor in Baker neither in Safari Mobile. Could you please explain how to make it work? Thank you :)

About the "bounce effect", that's really weird: since the horizontal scrolling is paginated, there shouldn't be any bounce while swiping through the pages. Can you explain it better and add some instruction to reproduce the bug (or a sample to see), since so far I was unable to do it?

By the way loading and managing more than 3 UIWebView may be too much for the device to handle, it's already hard to handle 3 of them at the same time :)

**Comment by mimetic** [comment] 2011-06-15 22:34
Swiping: OK, the JS swiping only happens in 0010.html and 0020.html files. Go to the "Fire" chapter, and you should be able to swipe to the left, showing the images.

Bounce: I don't think it is technically a "bounce." Rather, swiping a page _quickly_ makes it scroll just a little beyond the actual page. Try swiping very quickly. For that brief moment, the page beyond slides in, or nothing if there is no page to show. You can see this in most apps that scroll. I think it is not a bug, although it is odd. 
   scrollView.pagingEnabled = YES
should prevent this, by my reading, but I'm not a C programmer!

My pages are not supposed to be big, long pages, only screen size. Clearly, you can load screen sized pages without much trouble...other apps do it. 

I do wonder: my design creates a webview of a very large page. Maybe it takes a lot of memory to build & store a webview that is large in dimensions, e.g. 768 x 5000 pixels. There may be a smarter way to have images slide!

I have quickly tested very compact HTML pages that only have one big image, and they work nicely. I had to build this whole Javascript mess because, well, the three-cards was not working! If you look at my JS code, you'll see it is very close to yours, in function. Simple memory management, preloading of pages, etc.

Another reason to build the swiping pages into one HTML page is that I didn't want to have a hundred HTML pages to maintain, to build the book.

**Comment by folletto** [comment] 2011-06-15 22:40
The "scrollView.pagingEnabled = YES" command however will disable paging at all, so you won't have any more the automatically centered pagination. :)

About mantaining the pages... well it depends a lot on what you are doing. ;)

However, we'll test again, and please post here any new version that you are going to have, or even better maybe create a new Issue called JavaScript Pagination or something like that, so we can test out that road in a more precise way. :)

**Comment by mimetic** [comment] 2011-06-15 23:21
--- The "scrollView.pagingEnabled = YES" command however will disable paging at all, so you won't have any more the automatically centered pagination.

Huh. I use scrollView.pagingEnabled = YES, and it does not cause me a problem. So, I'm don't understand exactly what that means.

I think the Javascript scroll is a bad idea, frankly. I would much rather have that kind of thing be more native, more part of the fast, basic coding.

Regarding coding the pages, I am looking at a photo book! Baker is really not so good for this (yet), but I didn't know what else to do.

**Comment by folletto** [comment] 2011-06-15 23:26
Ha sorry, it's the exact opposite. Nevermind. ;)

There are published around some very fast javascript scrolling solutions for iPad, overriding the native scrolling, you might want to have a look at these. ;)

Well yes, if you are building a photobook, well, a horizontal photobook then it's probably not the perfect choice. However, did you try simpli having a wide page? :)

**Comment by folletto** [comment] 2011-09-05 22:43
Ok, Xmas completed this monumental task.

We have:
1. Three-cards support
2. Screenshot cache support (thanks to the PugPig team for the idea)

By default, we are using "Screenshot" modality, because it's cleaner, doesn't cause problems with preloaded pages that execute code on-load and uses less memory.
But of course, if you need it you can enable three-cards as well that we saw works well in some situations (including a published book), using this flag:

#define ENABLE_THREE_CARD NO

We also tested it, and feels stable. But of course please test as much as possible before the 3.0 release! :D

**Closed as completed by folletto** 2011-09-05 22:43 UTC
Labels: Feature

**Comment by frantovar** [comment] 2011-09-06 08:24
What good news!I will try! How I can get version 3.0?

## 

Francesc Tovar

**Comment by folletto** [comment] 2011-09-06 08:48
The simplest way is to click on "Source" above, then "Download" and pick the last master. Otherwise you can use git following the instructions on how to use it on this website. :)

**Comment by frantovar** [comment] 2011-09-06 08:49
Ok thanks!

## 

Francesc Tovar

**Comment by frantovar** [comment] 2011-09-06 10:26
Hi, i've tried to compile the last master and i recibe SIGABRT signal. ¿Some suggestions?

Thanks!

## 

Francesc Tovar

**Comment by Xm4s** [comment] 2011-09-06 11:03
Could you explain the steps to reproduce the bug ?
I have just tried to download the latest master branch and compile it with no problem, so I'm a bit clueless :)

One thing you may try is to clean the project (in Xcode click on Product --> Clean) but I don't know if this could help (but still is so quick you might as well give it a try)

Also be sure to have the latest stable version of the iOS SDK (4.3)

**Comment by frantovar** [comment] 2011-09-06 11:10
Hi Xm4s, 

I've tried with Xcode3 and 4. 

The console throw this message:

terminate called after throwing an instance of 'NSException'
warning: UUID mismatch detected with the loaded library - on disk is:
    /Developer/Platforms/iPhoneOS.platform/DeviceSupport/4.3.5 (8L1)/Symbols/Developer/usr/lib/libXcodeDebuggerSupport.dylib

**Comment by folletto** [comment] 2011-09-06 11:13
Does this help maybe: http://stackoverflow.com/questions/215252/uuid-mismatch-detected-with-the-loaded-library ?

**Comment by frantovar** [comment] 2011-09-06 11:49
Seems to be a problem with my installation. I tried on another computer and works fine. I'm going to reinstall Xcode, thanks!

**Comment by folletto** [comment] 2011-09-06 11:50
You're welcome! :)

**Comment by frantovar** [comment] 2011-09-06 12:57
Hello again,

On the other computer everything worked fine until we have included our own book inside the folder "book." Xcode displays error "PageTitleLabel.m"

NSRange matchRange = [[titleRegex firstMatchInString: FileContent options: 0 range: NSMakeRange (0, [FileContent length])] rangeAtIndex: 1];

Maybe i need change the "book.json" file?

Thanks!

**Comment by folletto** [comment] 2011-09-06 13:00
Could you please open a separate issue so we can track it accordingly? ;)

**Comment by frantovar** [comment] 2011-09-06 13:03
Ok sorry ;)
