### ISSUE TITLE
ios6 and xcode 4.5 Orientation bug

### ISSUE THREAD

**Issue by lepop** [Simbul/baker#493] opened 2012-09-20 13:58 UTC
Hello, with ios6 and xcode 4.5 i have only an vertical orientation. 
With ios5.1 its work fine.

Thanks

**Comment by folletto** [comment] 2012-09-20 15:45
Yes, unfortunately it's a known bug introduced with a low-level change in iOS6, we have to update that.

Some reference links on the issue:
- http://blog.hawkimedia.com/2012/08/ios6-ready/
- https://gist.github.com/3725118 (potential fix)
- http://dhilipsiva.blogspot.co.uk/2012/07/ios-6-ui-interface-orientation.html
- http://www.cocos2d-x.org/boards/6/topics/15447

**Comment by Xm4s** [comment] 2012-09-20 16:37
With the commit f4e332398771514a64ffee92898b30c2a61e5f3d orientation in iOS6 should work properly again.
Test it out and let us know the results :)

**Comment by marwol** [comment] 2012-09-20 17:15
It works for me in iOS 6 and iOS 5.

Thanks,

**Comment by Xm4s** [comment] 2012-09-20 17:21
I forgot to tell that for now the fix is only on the Master branch ... but I guess you already found it out :)

**Comment by hitchio** [comment] 2012-09-21 14:42
hello!
i cannot find the file "BakerViewController.m" within bakers 3.2. there is no such directory??
can you please explain, where i have to look for this file?
thanx 
regards
h

**Comment by folletto** [comment] 2012-09-21 14:46
Version 3.2 doesn't have it anymore. The current master version has been completely upgraded to be modular. :)
What are you trying to do? What you're looking for might be in `RootViewController`. ;)

**Comment by hitchio** [comment] 2012-09-21 14:54
it is, i changed the first part, but then it stopped at line 1851. i cannot make other changes running.
my problem is, that in baker 3.2 there´s no landscape modus. i made my book for landscape, but it is shown in ios6 in portait modus only, testing from xcode 4.5.

**Comment by folletto** [comment] 2012-09-21 14:56
Why aren't you just using the version on Master?

**Comment by hitchio** [comment] 2012-09-21 14:58
you mean downloading 3.2 again from bakers website?

**Comment by folletto** [comment] 2012-09-21 15:00
No I mean using the Master version from GitHub, with already the fixes in. The one where you commented as well. ;)
Click on _Code_ at the top and then _Zip_. :)

**Comment by hitchio** [comment] 2012-09-21 16:03
ok- sorry, i´m not used to github. it works now! thank you

**Comment by folletto** [comment] 2012-09-21 16:37
It's good to know, great! :)

**Comment by fmenossi** [comment] 2012-09-27 19:20
I got a problem on fullscreen videos. They became all black. is anyone dealing with this issue?

**Comment by folletto** [comment] 2012-09-27 19:21
If it's a new problem, please open a new issue and please please please describe _EXACTLY_ what happens, hopefully following these steps: https://github.com/Simbul/baker/wiki/It%27s-crashing%2C-exploding-or-any-other-issue
Thanks! :D

**Comment by tstegart** [comment] 2012-09-27 19:57
We've had it full screen videos turn black happen on an iPad 1. I haven't been able to narrow it down enough to open an issue on it because it seems random. I can't reproduce it.

**Comment by Simbul** [comment] 2012-09-27 20:38
We have tested the fix for the orientation bug and confirmed it works, so I'll be closing this issue.

**Closed as completed by Simbul** 2012-09-27 20:38 UTC
Labels: Bug

**Comment by fmenossi** [comment] 2012-09-27 20:55
Hi. Sorry for that. I'll do it next time.
I have a link here and then you can install it in your ipad. Can i Send you?
Thanks

**Comment by folletto** [comment] 2012-09-27 21:09
Please test as I linked you above and describe it clearly in a new issue, then we'll see if we need to see it. As I said I can't understand anything about the problem if you don't do these steps and describe it better. :)
