### ISSUE TITLE
Undeclare Identifier on BakerViewController.m

### ISSUE THREAD

**Issue by RattanakUNG** [Simbul/baker#641] opened 2013-01-16 09:42 UTC
Dear respecive,

I got this problem since my fresh download and run Baker framework.
Please see on my attached file.
![Screen Shot 2013-01-15 at 3 37 10 PM](https://f.cloud.github.com/assets/3013193/70767/f0c52818-5fc0-11e2-808c-febc050011b2.png)

Anyone have any idea,

Please help me out.
- (NSInteger)supportedInterfaceOrientations {
  if ([book.orientation isEqualToString:@"portrait"]) {
      return (UIInterfaceOrientationMaskPortrait | UIInterfaceOrientationMaskPortraitUpsideDown);
  } else if ([book.orientation isEqualToString:@"landscape"]) {
      return UIInterfaceOrientationMaskLandscape;
  } else {
      return UIInterfaceOrientationMaskAll;
  }
  }

**Comment by folletto** [comment] 2013-01-16 11:55
Could you please check this first and follow the instructions there?
https://github.com/Simbul/baker/wiki/Problems-and-Debugging

Thanks! :D

**Comment by RattanakUNG** [comment] 2013-01-16 14:38
Thank you very much,

But I still no luck on it...

It's a fresh download, and I already clean up the folder as well simulator...
or don't you have the same as my problem, do you? because it's a fresh download from "bakerframework.com" I haven't done anything yet just extract and run...

What else could I do then...?

**Comment by folletto** [comment] 2013-01-16 14:50
Yep, so far I can't reproduce that problem.

If you "just extracted and run" then... well you should have followed a tutorial... which tutorial did you follow? Newsstand or Standalone? :)

**Comment by RattanakUNG** [comment] 2013-01-16 14:59
I don't know yet,...

just download from http://bakerframework.com/down/baker-framework-4.0.zip as well from the github,
https://github.com/Simbul/baker/archive/master.zip  they both i got the same problem.
extract and run...

would you try this please, you may encounter the same as mind... or you may found different please update me.

Thanks,..

**Comment by folletto** [comment] 2013-01-16 15:12
Then, follow one of the two tutorials first: https://github.com/Simbul/baker/wiki :)
You can't run Baker from scratch without following one of the two tutorials. :)

**Comment by RattanakUNG** [comment] 2013-01-16 15:14
I got it,... I go along with standalone tutorial, but I found many issue on...

I just wonder, why baker just don't release a ready package one for standalone and Newsstand... that would much help i think,

or do you have one sir(a fixed package), may you share please.

Thanks...
Here is the screen shoot after all...
![Screen Shot 2013-01-16 at 10 20 23 PM](https://f.cloud.github.com/assets/3013193/71619/73d7b8cc-5ff0-11e2-8c5e-d58b9970d1e1.png)

**Comment by folletto** [comment] 2013-01-16 15:23
It's a good idea to release two packages, but still most of the things you have to do are configuration, so you will sill require a tutorial, but we'll think about it, thanks. :)

—

For the problem instead, please add more details. From what you write, still feels like a problem in the XCode or iOS SDK version you are using. As written in the tutorial Problems and Debugging, could you make sure that you are using the latest version of XCode/iOS?

**Comment by RattanakUNG** [comment] 2013-01-16 15:32
wow... Bakerframework is fantastic....
I just solve out the building fail problem, but I still got an issue on warning,...

May you help to sold out please 
Here is the attached file.
![Screen Shot 2013-01-16 at 10 28 46 PM](https://f.cloud.github.com/assets/3013193/71654/bcea346c-5ff1-11e2-966d-d80f821f8845.png)

Thank you very much folletto for accompany me for long... :)

**Comment by folletto** [comment] 2013-01-16 15:43
How did you solve the previous problem? Because even this seems like a version issue to tell the truth... :D 

Overall, however, warnings shouldn't be a problem. ;)

**Comment by RattanakUNG** [comment] 2013-01-16 15:57
hmm.... enjoying reading in simulator, just found out, I din't see any .xib file in the frame at all.,

how suppose could i integrate this framework to my existing project than...??

oh, solving problem I seem not sure does it right or not.. I just delete all those building fail command... :) 
What do you think?

**Comment by folletto** [comment] 2013-01-16 20:49
Why should you need a xib to integrate it? Just import the classes and load them. It's quite straightforward, even if we didn't test the import for the shelf, just for the book itself.

**Comment by folletto** [comment] 2013-02-11 22:22
I'm closing this issue since the discussion didn't progress. Reopen if needed. :)

**Closed as completed by folletto** 2013-02-11 22:22 UTC
Labels: Support
