### ISSUE TITLE
Download progress bar doesnt work properly

### ISSUE THREAD

**Issue by sempeck** [Simbul/baker#716] opened 2013-02-18 11:01 UTC
Hi Guys, 

I am testing Baker Shelf and have this strange issue. When I am downloading my magazine the progress bar is blank for few minutes, and then, at the end of download, it turns red at once. I think this might be confusing for user - not seeing the download progress. 

Have anyone experienced that? Would you have any solutions? Advices?

Or maybe it could be a server side problem?

Thank you

**Comment by Simbul** [comment] 2013-03-05 01:04
Is this still happening with the latest `master`? What's the message next to the bar while it is blank?

**Comment by Simbul** [comment] 2013-03-11 22:32
Most likely connected to #752.

**Comment by Simbul** [comment] 2013-03-18 23:16
Closing as 2 weeks went by with no followup.

As an aside, a partial solution might be to show the number of downloaded Kb along with the progress bar: this way even when the total number of Kb is not available, something would still happen in the UI to tell users that download is progressing.

**Closed as completed by Simbul** 2013-03-18 23:16 UTC
Labels: Waiting follow-up

**Comment by sempeck** [comment] 2013-03-19 08:59
Hey,
sorry I haven't follow up.
The thing is I used the most recent master and the situation hasn't changed. There is no message next to the bar, nor showing the progress. 
It might be the server side problem, but I still couln't find the answer.
Regards.

**Comment by Simbul** [comment] 2013-03-19 09:50
I think the cause might be the same one as in issue #752. Unfortunately there's not much we can do (save for the partial solution I sketched above) as it's a server problem.

**Comment by JosephMacReady** [comment] 2013-05-06 10:28
What should I do to fix this?

**Comment by JosephMacReady** [comment] 2013-05-06 10:34
Server-wise or the option you mentioned that is
