### ISSUE TITLE
Problems showing index.html menu

### ISSUE THREAD

**Issue by vladimirt2000** [Simbul/baker#743] opened 2013-02-28 18:47 UTC
I have problems with the menu after double tap the screen.
The first time the app shows, theres no problem with menu visualization.
If you click on Home button, and after that, open the app again, you see the screen shifted to top about 15 pixels, and you can see the index menu appearing from bottom.
I attach 2 pictures showing the behavior.
![photo](https://f.cloud.github.com/assets/1194244/206659/3de27302-81d7-11e2-9fe5-559fbbadd379.PNG)
![photo-1](https://f.cloud.github.com/assets/1194244/206663/47d1683c-81d7-11e2-858c-2b2a38b016a7.PNG)

**Comment by folletto** [comment] 2013-02-28 19:12
Could you please follow first the [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) page on the wiki and report your findings here? :)

**Comment by vladimirt2000** [comment] 2013-02-28 19:57
I did all the Problems and Debugging and still with the same problem.
I downloaded the Master version from Github, downloades the Study in Scarlet book, run on Simulator, and the same issue, the second time, opening the app, the page shift to top.
I'm using XCode 4.6.
Any clues?

**Comment by folletto** [comment] 2013-02-28 20:37
If you followed that, you _surely_ have seen that really nice step 3 saying "Include the full debug log"... ;)

**Comment by vladimirt2000** [comment] 2013-02-28 21:42
Yes, you're right. Here is the debug window contents.
2013-02-28 18:33:33.894 Uai Ucla[196:907] ====== Newsstand is not enabled ======
2013-02-28 18:33:33.916 Uai Ucla[196:907] Validating book JSON param "-baker-index-height"
2013-02-28 18:33:33.919 Uai Ucla[196:907] Validating book JSON param "title"
2013-02-28 18:33:33.920 Uai Ucla[196:907] Validating book JSON param "-baker-background"
2013-02-28 18:33:33.922 Uai Ucla[196:907] Validating book JSON param "-baker-index-bounce"
2013-02-28 18:33:33.923 Uai Ucla[196:907] Validating book JSON param "contents"
2013-02-28 18:33:33.924 Uai Ucla[196:907] Validating book JSON param "url"
2013-02-28 18:33:33.926 Uai Ucla[196:907] Validating book JSON param "-baker-rendering"
2013-02-28 18:33:33.927 Uai Ucla[196:907] Validating book JSON param "-baker-media-autoplay"
2013-02-28 18:33:33.929 Uai Ucla[196:907] Validating book JSON param "-baker-background-image-portrait"
2013-02-28 18:33:33.930 Uai Ucla[196:907] Validating book JSON param "-baker-page-numbers-color"
2013-02-28 18:33:33.932 Uai Ucla[196:907] Validating book JSON param "creator"
2013-02-28 18:33:33.933 Uai Ucla[196:907] Validating book JSON param "author"
2013-02-28 18:33:33.935 Uai Ucla[196:907] Validating book JSON param "zoomable"
2013-02-28 18:33:33.936 Uai Ucla[196:907] Validating book JSON param "hpub"
2013-02-28 18:33:33.937 Uai Ucla[196:907] Validating book JSON param "-baker-vertical-bounce"
2013-02-28 18:33:33.938 Uai Ucla[196:907] Validating book JSON param "-baker-background-image-landscape"
2013-02-28 18:33:33.940 Uai Ucla[196:907] Validating book JSON param "date"
2013-02-28 18:33:33.941 Uai Ucla[196:907] Validating book JSON param "orientation"
2013-02-28 18:33:33.971 Uai Ucla[196:907] JSON Parsed successfully, book "catalogo-mba-uai-ucla-1a815962fd6738e - Catalogo MBA UAI UCLA" created
2013-02-28 18:33:33.975 Uai Ucla[196:907] Cover not specified for catalogo-mba-uai-ucla-1a815962fd6738e, probably missing from book.json
2013-02-28 18:33:33.980 Uai Ucla[196:907] • INIT
2013-02-28 18:33:33.983 Uai Ucla[196:907]     Device Width: 768.000000
2013-02-28 18:33:33.984 Uai Ucla[196:907]     Device Height: 1024.000000
2013-02-28 18:33:34.039 Uai Ucla[196:907] Successfully added skip backup attribute to item /var/mobile/Applications/84582B9D-21B0-48FE-887F-24017AD28BCD/Library/Caches/statuses (iOS >= 5.1)
2013-02-28 18:33:34.045 Uai Ucla[196:907] Successfully added skip backup attribute to item /var/mobile/Applications/84582B9D-21B0-48FE-887F-24017AD28BCD/Library/Caches/statuses/catalogo-mba-uai-ucla-1a815962fd6738e.json (iOS >= 5.1)
2013-02-28 18:33:34.047 Uai Ucla[196:907] STATUS: page: (null)
2013-02-28 18:33:34.049 Uai Ucla[196:907] STATUS: scrollIndex: (null)
2013-02-28 18:33:34.079 Uai Ucla[196:907] • LOAD BOOK WITH PATH: /var/mobile/Applications/84582B9D-21B0-48FE-887F-24017AD28BCD/Uai Ucla.app/books/catalogo
2013-02-28 18:33:34.080 Uai Ucla[196:907] • Reset leftover page slot
2013-02-28 18:33:34.082 Uai Ucla[196:907] • Reset page details array and empty screenshot directory
2013-02-28 18:33:34.089 Uai Ucla[196:907]     Pages in this book: 21
2013-02-28 18:33:34.091 Uai Ucla[196:907] Screenshots are stored in /var/mobile/Applications/84582B9D-21B0-48FE-887F-24017AD28BCD/Library/Caches/screenshots/catalogo-mba-uai-ucla-1a815962fd6738e
2013-02-28 18:33:34.153 Uai Ucla[196:907] Device and book orientations are in sync
2013-02-28 18:33:34.156 Uai Ucla[196:907] • Set size for orientation: portrait
2013-02-28 18:33:34.158 Uai Ucla[196:907] • Set tappable area size
2013-02-28 18:33:34.160 Uai Ucla[196:907]     Prevent page from changing until layout is updated
2013-02-28 18:33:34.161 Uai Ucla[196:907] • Show page details for the book pages
2013-02-28 18:33:34.163 Uai Ucla[196:907]     Unlock page changing
2013-02-28 18:33:34.167 Uai Ucla[196:907] • Init page details for the book pages
2013-02-28 18:33:34.339 Uai Ucla[196:907] Set IndexView size to 768x1024, with pageY set to -20
2013-02-28 18:33:34.389 Uai Ucla[196:907] Path to index view is /var/mobile/Applications/84582B9D-21B0-48FE-887F-24017AD28BCD/Uai Ucla.app/books/catalogo/index.html
2013-02-28 18:33:34.393 Uai Ucla[196:907] Path to index view is /var/mobile/Applications/84582B9D-21B0-48FE-887F-24017AD28BCD/Uai Ucla.app/books/catalogo/index.html
2013-02-28 18:33:34.395 Uai Ucla[196:907] • Add page to the loding queue
2013-02-28 18:33:34.396 Uai Ucla[196:907] • Add page to the loding queue
2013-02-28 18:33:34.397 Uai Ucla[196:907] • Handle loading of slot 0 with page 1
2013-02-28 18:33:34.398 Uai Ucla[196:907] • Setup new page for loading
2013-02-28 18:33:34.409 Uai Ucla[196:907] • Setup webView
2013-02-28 18:33:34.412 Uai Ucla[196:907] • Loading: book/01.html
2013-02-28 18:33:34.930 Uai Ucla[196:907] • Should webView load the page ?
2013-02-28 18:33:34.931 Uai Ucla[196:907]     Page is current page and current page IS delaying loading --> load page
2013-02-28 18:33:34.933 Uai Ucla[196:907] • Page did start load
2013-02-28 18:33:35.576 Uai Ucla[196:907] Set size for IndexView to 768x140 (constrained from 3558x140)
2013-02-28 18:33:36.117 Uai Ucla[196:907] • Page did finish load
2013-02-28 18:33:36.119 Uai Ucla[196:907] • Setting current page height from 0 to 1024.000000
2013-02-28 18:33:36.121 Uai Ucla[196:907] • webView hidden: 0 animating: 1
2013-02-28 18:33:36.123 Uai Ucla[196:907] • Handle loading of slot 1 with page 2
2013-02-28 18:33:36.124 Uai Ucla[196:907] • Setup new page for loading
2013-02-28 18:33:36.133 Uai Ucla[196:907] • Setup webView
2013-02-28 18:33:36.137 Uai Ucla[196:907] • Loading: book/02.html
2013-02-28 18:33:36.153 Uai Ucla[196:907] • Paging for current page is enabled = 0
2013-02-28 18:33:36.353 Uai Ucla[196:907] • Should webView load the page ?
2013-02-28 18:33:36.354 Uai Ucla[196:907]     Page is next page --> load page
2013-02-28 18:33:36.356 Uai Ucla[196:907] • Page did start load
2013-02-28 18:33:36.703 Uai Ucla[196:907]    Handle last scroll index if necessary
2013-02-28 18:33:36.740 Uai Ucla[196:907] • Page did finish load
2013-02-28 18:33:36.742 Uai Ucla[196:907] • webView hidden: 0 animating: 1
2013-02-28 18:33:36.745 Uai Ucla[196:907] • Paging for current page is enabled = 0
2013-02-28 18:33:47.968 Uai Ucla[196:907] • Scrollview will begin dragging
2013-02-28 18:33:47.972 Uai Ucla[196:907] • User scroll
2013-02-28 18:33:47.982 Uai Ucla[196:907] • User scroll
2013-02-28 18:33:47.996 Uai Ucla[196:907] • User scroll
2013-02-28 18:33:48.013 Uai Ucla[196:907] • User scroll
2013-02-28 18:33:48.028 Uai Ucla[196:907] • User scroll
2013-02-28 18:33:48.044 Uai Ucla[196:907] • User scroll
2013-02-28 18:33:48.060 Uai Ucla[196:907] • Scrollview did end dragging
2013-02-28 18:33:48.065 Uai Ucla[196:907] • Scrollview will begin decelerating
2013-02-28 18:33:48.067 Uai Ucla[196:907] • User scroll
2013-02-28 18:33:48.468 Uai Ucla[196:907] • Swiping to page: 2
2013-02-28 18:33:48.470 Uai Ucla[196:907] • Goto page: book/02.html
2013-02-28 18:33:48.509 Uai Ucla[196:907]     Tap number: 1
2013-02-28 18:33:48.511 Uai Ucla[196:907] • Setting current page height from 1024 to 1024.000000
2013-02-28 18:33:48.512 Uai Ucla[196:907] • Add page to the loding queue
2013-02-28 18:33:48.513 Uai Ucla[196:907] • Handle loading of slot 1 with page 3
2013-02-28 18:33:48.514 Uai Ucla[196:907] • Setup new page for loading
2013-02-28 18:33:48.524 Uai Ucla[196:907] • Setup webView
2013-02-28 18:33:48.527 Uai Ucla[196:907] • Loading: book/03.html
2013-02-28 18:33:48.602 Uai Ucla[196:907] • Should webView load the page ?
2013-02-28 18:33:48.604 Uai Ucla[196:907]     Page is next page --> load page
2013-02-28 18:33:48.605 Uai Ucla[196:907] • Page did start load
2013-02-28 18:33:48.911 Uai Ucla[196:907] • Page did finish load
2013-02-28 18:33:48.913 Uai Ucla[196:907] • webView hidden: 0 animating: 1
2013-02-28 18:33:48.916 Uai Ucla[196:907] • Paging for current page is enabled = 0
2013-02-28 18:33:53.158 Uai Ucla[196:907] • User tap at [547.000000, 416.000000]
2013-02-28 18:33:53.350 Uai Ucla[196:907] • User tap at [552.000000, 411.000000]
2013-02-28 18:33:53.351 Uai Ucla[196:907]     Multi Tap TOGGLE STATUS BAR
2013-02-28 18:33:53.352 Uai Ucla[196:907] • Toggle bars visibility
2013-02-28 18:33:59.313 Uai Ucla[196:907] • User tap at [542.000000, 439.000000]
2013-02-28 18:33:59.504 Uai Ucla[196:907] • User tap at [549.000000, 434.000000]
2013-02-28 18:33:59.506 Uai Ucla[196:907]     Multi Tap TOGGLE STATUS BAR
2013-02-28 18:33:59.507 Uai Ucla[196:907] • Toggle bars visibility
2013-02-28 18:34:03.369 Uai Ucla[196:907] RESIGN, SAVING
2013-02-28 18:34:03.383 Uai Ucla[196:907] saved status
2013-02-28 18:35:01.582 Uai Ucla[196:907] • User tap at [476.000000, 619.000000]
2013-02-28 18:35:01.774 Uai Ucla[196:907] • User tap at [472.000000, 618.000000]
2013-02-28 18:35:01.775 Uai Ucla[196:907]     Multi Tap TOGGLE STATUS BAR
2013-02-28 18:35:01.776 Uai Ucla[196:907] • Toggle bars visibility
2013-02-28 18:35:02.880 Uai Ucla[196:907] • User tap at [465.000000, 555.000000]
2013-02-28 18:35:03.071 Uai Ucla[196:907] • User tap at [470.000000, 536.000000]
2013-02-28 18:35:03.072 Uai Ucla[196:907]     Multi Tap TOGGLE STATUS BAR
2013-02-28 18:35:03.073 Uai Ucla[196:907] • Toggle bars visibility

When I click Home button, generates 2 actions: RESIGN, SAVING; and saved status
After opening the same app, the 2nd time, there's no debug error or message, and the window appears with the issue.
After that I only double tap to check if the TOC works. It works, but still with the issue.

**Comment by folletto** [comment] 2013-02-28 23:17
Thanks! I see that there are some interesting elements, but we have to look into it. Actually it's a bug that we thought we have solved, but from what I see it appear to be still there.

We'll look into it, thanks. :)

**Comment by buildc0de** [comment] 2013-03-02 21:34
Sounds like a duplicate of issue #584? The pull request #675 is still open...

**Comment by folletto** [comment] 2013-03-02 21:48
You're right, might be. :)

**Comment by Simbul** [comment] 2013-03-18 23:29
@vladimirt2000 did you solve it in the end?

**Comment by benoitchantre** [comment] 2013-03-20 09:31
It should be solved with the fix from waywalker (it was merged in the master branch after this issue was opened).
@vladimirt2000, can you confirm that?

There's another issue with the index position (20px moved down) that appears only when you launch the app (not when it comes from the background), but this will be described in a new issue.

**Comment by vladimirt2000** [comment] 2013-03-20 16:15
I'll try with the new changes you made.
The master always includes the last commits?

**Comment by buildc0de** [comment] 2013-03-20 22:31
#675 has been merged into master. There is an additional improvement #763 that hasn't been merged yet...

**Comment by Simbul** [comment] 2013-03-23 14:24
#763 has now been merged. Can we double check if it fixes the issue so we can close it down? :)

**Comment by benoitchantre** [comment] 2013-03-24 16:43
I wasn't able to reproduce this issue with the book _A Study in Scarlet_, but in the case you have an index that need full height, you will have something as described in #774.

@vladimirt2000, can you try with your project?

**Comment by vladimirt2000** [comment] 2013-03-24 18:38
I've tryed with A study in Scarlet and with my project and now are working fine. I have to do one more test with the last iOS update 6.1.3. I'll do it tonight.

**Comment by Simbul** [comment] 2013-03-25 21:48
Neat! I'll close the issue then, seeing that the outstanding bugs are already tracked elsewhere.

**Closed as completed by Simbul** 2013-03-25 21:48 UTC
Labels: Bug, Investigation Required, Waiting follow-up
