### ISSUE TITLE
page down and page up tap areas/scrolling

### ISSUE THREAD

**Issue by anjimi** [Simbul/baker#572] opened 2012-12-05 13:51 UTC
I have an issue in Baker 4.0 with the page vertical scrolling and up/down tap areas.

This is happening in iPhone & iPad simulator & device, iOS 5 & 6.

Tap DOWN scrolls the page down 50px less than actual page height.
iPad simulator Xcode output:
2012-12-05 13:44:46.206 Anfield Wrap[16982:1a303]     Tap DOWN \/
2012-12-05 13:44:46.206 Anfield Wrap[16982:1a303] • Scrolling page down to 974

Tap UP scrolls the page up 50px less than actual page height.
iPad simulator Xcode output:
2012-12-05 13:45:22.150 Anfield Wrap[16982:1a303]     Tap UP /!
2012-12-05 13:45:22.150 Anfield Wrap[16982:1a303] • Scrolling page up to 50

Touch the screen again and the vertical position corrects itself.

It also appears the Tap Down and Tap Up areas are also positioned 50px lower than they should be, but only on portrait orientation. On landscape orientation the tap areas are positioned correctly but the scrolling is still 50px off.

**Comment by anjimi** [comment] 2012-12-11 13:20
I have just updated to the most up-to-date master and I am still getting this problem. I have also tested this with the Baker example book, after adding the line '"-baker-vertical-pagination": true' in its book.json.

The same thing is happening, Tap DOWN scrolls the page down 50px less than actual page height,  Tap UP scrolls the page up 50px less than actual page height. Touch the screen again and the vertical position corrects itself.

I have found this in BakerViewController.m:

> ```
>   if (CGRectContainsPoint(upTapArea, tapPoint)) {
>       NSLog(@"    Tap UP /\\!");
>       [self scrollUpCurrentPage:([self getCurrentPageOffset] - pageHeight + 50) animating:YES];
>   } else if (CGRectContainsPoint(downTapArea, tapPoint)) {
>       NSLog(@"    Tap DOWN \\/");
>       [self scrollDownCurrentPage:([self getCurrentPageOffset] + pageHeight - 50) animating:YES];
> ```

I removed '+ 50' and '- 50' and the page scroll is now positioning correctly, but on portrait view the tap areas are still offset down the page by what seems to be about 50px. This is also happening with the Baker example book.

I have also discovered that if you rotate to landscape orientation, the tap areas are positioned correctly, and if you then rotate back to portrait, the position of the tap areas is fixed. I hadn't noticed this before.

This is really puzzling... I wasn't getting this problem with Baker 3.2.

**Comment by Simbul** [comment] 2013-01-05 17:23
The "missing" 50px are actually a feature, not a bug: this is to give the user a reference when scrolling. If we were to scroll down/up the entire page height, the user would see a new page and potentially wonder whether she lost some content in the transition.

As for the tap areas positioning, I'm not sure I'm getting what the issue is. Do you mean that the scroll action is triggered by tapping in an unexpected area of the screen?

**Comment by anjimi** [comment] 2013-01-08 09:31
I don't seem to be getting the issue with the tap areas with the most recent download of Baker. I have removed the 50px offset for our app as it is formatted with distinct vertical pages, though I can see how the 50px offset would be beneficial for a more book-like publication.

**Comment by folletto** [comment] 2013-02-11 22:35
This issue seems closed... I'm closing it. ;)

**Closed as completed by folletto** 2013-02-11 22:35 UTC
Labels: Waiting follow-up
